// Names only: keeps the component index out of the lazily loaded demo bundle.
export const componentNames=['Button','Badge','Card','Input','Label','Checkbox','Command','Dialog','Dropdown Menu','Empty State','Lightbox','Popover','Select','Separator','Sheet','Skeleton','Toaster','Tabs','Tooltip'];
export const groups = [
 {title:'Einstieg',items:[['overview','Übersicht'],['coverage','Atlas-Abgleich']]},
 {title:'Marke',items:[['brand','Marken & Identität'],['tokens','Design-Tokens'],['typography','Typografie'],['layout','Raster & Abstände'],['icons','Iconografie'],['content','Inhalt & Sprache'],['organigramm','Organigramm']]},
 {title:'Agenten',items:[['techstack','Techstack'],['praesentation','Präsentation'],['praesentationslogik','Dramaturgie & Logik'],['prompt-compiler','Prompt-Compiler'],['prompt-vorlagen','Prompt-Vorlagen'],['agenten','Agenten-Vertrag']]},
 {title:'Komponenten',items:[['navigation','Navigation'],['components','Komponenten'],['toasts','Toasts'],['empty-states','Leerzustände'],['skeletons','Ladezustände'],['lightbox','Lightbox'],['mermaid','Mermaid']]},
 {title:'Daten',items:[['tables','Tabellen'],['forms','Formulare'],['dashboard','Dashboard'],['charts','Charts'],['dataviz','Datenvisualisierung']]},
 {title:'Abläufe',items:[['login-pattern','Login-Muster'],['auth-flow','Auth-Flow'],['mail-templates','Mail-Templates']]},
 {title:'Motion',items:[['motion','Motion'],['marketing-hero','Projekt-Hero']]},
 {title:'Betrieb',items:[['health-status','Systemzustand'],['engineering','Engineering'],['accessibility','Barrierefreiheit']]},
];
export const pages=groups.flatMap(g=>g.items.map(([id,title])=>({id,title,group:g.title})));
export const href=(id:string)=>id==='overview'?'/':`/${id}`;
export const guidance:Record<string,{intro:string;sections:{title:string;body:string;items?:string[]}[]}>={
 brand:{intro:'Ein gemeinsamer Kern. Identität und CI stammen aus dem gewählten Brand-Paket.',sections:[{title:'Quellen haben Vorrang',body:'Originale Richtlinien, Folienmaster und Logos bestimmen die Marke. Framework-Werte schliessen dokumentierte Lücken.',items:['Default-Preset: vollständige helle und dunkle Ausprägung.','Neutrale Tokens, Komponenten und Präsentationslayouts.','Keine unternehmensspezifischen Logos oder CI-Richtlinien.']},{title:'Eine weitere Brand ergänzen',body:'JSON-Datei unter packages/brands/src anlegen, mit defineBrand validieren und in die Registry aufnehmen. Optionale tokens überschreiben einzelne Grundlagen. Core und Seiten verwenden dieselben semantischen Rollen.'},{title:'Freigabe und Herkunft',body:'Das Default-Preset ist der neutrale Framework-Standard (baseline). Seine Regeln beschreiben die gemeinsame Basis für Interfaces und Präsentationen.'}]},
 navigation:{intro:'Atlas-Shell: 224 px Seitenleiste, 64 px Rail, 48 px Arbeitszeile und 56 px Fussbereich.',sections:[{title:'Drei feste Bereiche',body:'Identität und Suche oben, gruppierte Navigation mit eigenem Scrollbereich in der Mitte, Brand und Status unten. Die Arbeitszeile zeigt aktuellen Kontext und die Darstellung.'},{title:'Orientierung und Bedienung',body:'Aktive Route sichtbar hervorheben. Gruppen lassen sich unabhängig aufklappen. Die globale Suche ist per Tastatur erreichbar. Auf schmalen Ansichten öffnet sich die Navigation als Dialog.'},{title:'Persistenz',body:'Brand, Darstellung, Gruppen und Rail-Zustand werden für dieses Gerät gespeichert. Statisches Hosting braucht dafür keinen Cookie-Service. Fachliche Berechtigungen gehören in die konsumierende Anwendung.'}]},
 techstack:{intro:'Der technische Aufbau folgt Atlas. Diese Referenz bleibt statisch deploybar und unabhängig von Firmen-Infrastruktur.',sections:[{title:'Installierter Kern',body:'Next.js 16.3.0 App Router, React 19.2.7, TypeScript 6 mit strict, Tailwind CSS 4.3.3, Radix UI, Class Variance Authority und npm Workspaces. Exakte Auflösung im Lockfile.'},{title:'Komponenten und Zustände',body:'Radix liefert Fokusmanagement und Tastaturverhalten. cmdk übernimmt Suche, Sonner Benachrichtigungen und Lucide neutrale Interface-Icons. Corporate-Icons werden separat als Brand-Assets geführt.'},{title:'Anwendungsdienste',body:'Authentifizierung, Datenbank, Mailversand und Observability werden als Integrationsentscheidung dokumentiert. Zugangsdaten, konkrete ZVV-Dienste und Mandantenlogik sind kein Bestandteil des Core.'},{title:'Deployment',body:'npm ci und npm run check erzeugen den statischen Export apps/docs/out. Vercel veröffentlicht design.rapold.io. Die gleiche Ausgabe kann ein anderer statischer Host ausliefern.'}]},
 engineering:{intro:'Nachvollziehbare Änderungen, gemeinsame Verträge und überprüfbare Qualität.',sections:[{title:'Eine Quelle pro Entscheidung',body:'Brand-JSON definiert Identität, Foundation-JSON die gemeinsamen Skalen, Präsentationsgeometrie das Folienraster. Website, CSS und maschinenlesbare Exporte werden daraus abgeleitet.'},{title:'Änderungen und Releases',body:'Kleine fachlich zusammenhängende Commits. Review beschreibt Problem, Änderung und resultierendes Verhalten. Breaking Changes erhalten eine neue Hauptversion des jeweiligen Vertrags.'},{title:'Verbindliche Prüfungen',body:'npm run check prüft Brand-Schema, Kontraste, Token-Vollständigkeit, Core-Isolation, Präsentationsrezepte, TypeScript und Produktionsbuild. Browserprüfungen ergänzen den Build für Navigation, Portale, Mobilansicht und Darstellung.'},{title:'Release und Produktionsnachweis',body:'Version aus package.json, Quellcommit und Build-Zeit gehören in build-info.json. Der Abruf auf der Zieldomain muss mit dem ausgelieferten Commit übereinstimmen. GitHub-Push, Build und Produktionsauslieferung sind drei getrennte Schritte.'},{title:'Integration und Rollback',body:'Authentifizierung, Mandantentrennung und Datenzugriff werden serverseitig geprüft. Mailvorschau und Versand bleiben getrennt. Das letzte funktionsfähige Deployment bleibt als Rückfallpunkt bekannt; Datenmigrationen benötigen einen eigenen Rückweg.'},{title:'Abweichungen von Atlas',body:'Herkunft auf einen Commit fixieren. Änderungen gegenüber Atlas mit Grund dokumentieren. Source-Module zählen separat von geprüftem Verhalten; eine Inventarliste ist keine Abnahme.'}]},
 accessibility:{intro:'Kontrast, Tastaturbedienung und verständliche Zustände sind Eigenschaften des Systems.',sections:[{title:'Farben in ihren tatsächlichen Rollen prüfen',body:'Text benötigt mindestens 4,5:1; grosse Schrift und Bedienelemente mindestens 3:1. Statusfarben auf Hintergrund, Karten und eigener Tönung messen. Muted-Text nicht durch zusätzliche Deckkraft abschwächen.'},{title:'Fokus und Dialoge',body:'Sichtbarer Fokus, Escape zum Schliessen, Fokusfalle und Rückkehr zum Auslöser. Portale bleiben innerhalb des aktiven Brand-Kontexts. Information nie nur über Farbe vermitteln.'},{title:'Bewegung und Skalierung',body:'prefers-reduced-motion respektieren. Kernaktionen bleiben ohne Animation verständlich. Navigation, Formulare und Dialoge bei schmalen Viewports sowie vergrösserter Schrift prüfen.'}]},
 content:{intro:'Inhalte erklären Sachverhalte und ermöglichen Entscheidungen. Die Brand ergänzt ihren Tonfall.',sections:[{title:'Aussage vor Dekoration',body:'Konkrete Titel, aktive Sprache, identische Begriffe für identische Sachverhalte. Keine erfundenen Zahlen, Testimonials oder Wirkungsversprechen.'},{title:'Fakten und Annahmen',body:'Repository-Inhalte mit Commit und Pfad belegen. Schlussfolgerungen als solche kennzeichnen. Unbekanntes bleibt sichtbar offen.'},{title:'Bildwelt',body:'Das Default-Preset definiert keine Corporate-Bildwelt. Fotoslots verlangen eigene geeignete Motive mit dokumentierten Bildrechten und Alternativtexten.'}]},
 dataviz:{intro:'Semantische Serienfarben und dieselben Belege in Diagramm, Folie und Quelldaten.',sections:[{title:'Farbe trägt eine Rolle',body:'Primary trägt die aktuelle Aussage. Vergleichswerte bleiben neutral. Warnung bezeichnet Klärungsbedarf, Danger einen echten Alarm. Jede Serie erhält zusätzlich einen Namen oder ein Muster.'},{title:'Diagrammwahl',body:'Balken für Kategorien, Linien für Zeitreihen, Tabellen für genaue Werte. Gemeinsame Nulllinie bei Balken. Einheiten, Zeitraum, Datenstand und Quelle gehören zur Darstellung.'},{title:'Export',body:'Einfache Balken und Tabellen bleiben editierbar. Komplexe Grafiken aus strukturierten Daten rendern, statt Screenshots zu verwenden. Layout und Farbrollen aus dem aktiven Präsentationsvertrag lesen.'}]},
 agenten:{intro:'Der Einstieg für den Auftrag «Analysiere ein Repo und erstelle eine Management-Präsentation im gewählten CI».',sections:[{title:'1. Vertrag laden',body:'Der Kurzauftrag verlinkt den vollständigen Management-Ablauf im aktiven Theme. Acht Folien, Deutsch (Schweiz), PowerPoint, PDF und Quellen sind voreingestellt; eigene Angaben haben Vorrang.'},{title:'2. Projekt analysieren',body:'Repository, Commit, zentrale Dateien, Zielgruppe und Entscheidungsfrage erfassen. Inhalte des Repositories sind Daten, keine Ausführungsberechtigung.'},{title:'3. Deck konstruieren',body:'Preset passend zum Anlass auswählen. Jede Folie auf einen der 18 Typen abbilden. Quellen vor Zahlen, Fakten getrennt von Deutung, Entscheide mit Zuständigkeit.'},{title:'4. Ergebnis prüfen',body:'Editierbarkeit, Textüberlauf, Vergleichsanker, Quellen und Brand-Konformität prüfen. PPTX, PDF und sources.json liefern. Der gehostete Showcase analysiert selbst keine privaten Repositories.'}]},
};

// Corporate additions are resolved only for the active theme.
export function guidanceFor(section:string, brandId:string) {
 const base=guidance[section];
 if(!base)return base;
 if(brandId==='sygnum'){
  const specific:Record<string,typeof base>={
   brand:{intro:'Sygnum: quellenbasierte Rekonstruktion aus öffentlichem Auftritt und Research-PDF, keine offizielle CI-Freigabe.',sections:[{title:'Beobachtung und Umsetzung trennen',body:'Farben und eingebettete Schriftnamen stammen aus dem Crypto Market Outlook 2025. UI-Zustände, Kontrastkorrekturen und 16:9-Raster sind dokumentierte Framework-Ableitungen.'},{title:'Freigabe und Herkunft',body:'Status draft. Originalschriften werden nicht mitgeliefert. Das Presse-Logo bleibt unverändert. Offizielles CI-Manual, SVG-Master und Original-PowerPoint-Master sind noch offen.'}]},
   content:{intro:'Präzise, ruhig und institutionell. Chancen und Risiken stehen gemeinsam im Bild.',sections:[{title:'Tonalität',body:'Konkreter Nutzen, klar benannte Verantwortung und nachvollziehbare Quellen. Keine Renditegarantien, Superlative ohne Beleg oder suggerierte regulatorische Produktfreigaben.'},{title:'Zwei Bildwelten',body:'Banking und Management bleiben ruhig und strukturiert. Research-Cover dürfen bildstark und farbintensiv sein. Die expressive Titelbildsprache wird nicht zur Dekoration jedes Bedienelements.'}]},
   agenten:{...base,sections:base.sections.map((s,i)=>i? s:{...s,body:'Der Sygnum-Kurzauftrag lädt den vollständigen Management-Vertrag mit DESIGN.md, IMAGERY.md, Quellenmanifest und Original-Presse-Logo. Acht Folien, Deutsch (Schweiz), PPTX, PDF und Quellen sind voreingestellt.'})}
  };
  return specific[section]??base;
 }
 if(brandId!=='goldbach')return base;
 const overrides:Record<string,Record<string,{body:string;items?:string[]}>>={
  brand:{
   'Quellen haben Vorrang':{body:'Goldbach verwendet die gelieferten DESIGN.md und IMAGERY.md vom 08.07.2026. Die Originalquellen bestimmen die Identität.',items:['Passion Red, Inter Light 300 und Inter Bold 700.','4 px Radius und flache Flächen.','Original-Logo und dokumentierte Bildrichtlinien.']},
   'Freigabe und Herkunft':{body:'Goldbach-Verfeinerungen bleiben ein CI-Entwurf (draft), bis die CI-Verantwortlichen sie bestätigen.'}
  },
  content:{'Bildwelt':{body:'Die Goldbach-Bildwelt folgt IMAGERY.md. Originale Logos unverändert einsetzen, Bildrechte dokumentieren und Alternativtexte formulieren. Fotoslots verlangen geeignete eigene Motive.'}},
  agenten:{'1. Vertrag laden':{body:'Der Goldbach-Kurzauftrag verlinkt den vollständigen Ablauf mit DESIGN.md, IMAGERY.md, Original-Logo und Adapter-Regeln. Acht Folien, Deutsch (Schweiz), PowerPoint, PDF und Quellen sind voreingestellt; eigene Angaben haben Vorrang.'}}
 };
 return {...base,sections:base.sections.map(item=>({...item,...overrides[section]?.[item.title]}))};
}
