'use client';
import {useState} from 'react';
import {Inbox} from 'lucide-react';
import {toast} from 'sonner';
import * as UI from '@rapold/framework-core';
export const componentNames=['Button','Badge','Card','Input','Label','Checkbox','Command','Dialog','Dropdown Menu','Empty State','Lightbox','Popover','Select','Separator','Sheet','Skeleton','Toaster','Tabs','Tooltip'];
export function ComponentDemo(){
 const [value,setValue]=useState(''),[done,setDone]=useState(false);
 return <div className="demo-grid">
 <section className="demo-panel"><h2>Button & Badge</h2><div className="demo-row"><UI.Button onClick={()=>toast.success('Aktion ausgeführt')}>Primäraktion</UI.Button><UI.Button variant="secondary">Sekundär</UI.Button><UI.Button variant="outline">Outline</UI.Button><UI.Button variant="ghost">Ghost</UI.Button><UI.Button variant="destructive">Löschen</UI.Button><UI.Button disabled>Deaktiviert</UI.Button></div><div className="demo-row"><UI.Badge>Aktiv</UI.Badge><UI.Badge variant="secondary">Entwurf</UI.Badge><UI.Badge variant="destructive">Fehler</UI.Badge></div></section>
 <section className="demo-panel"><h2>Input, Label & Checkbox</h2><form onSubmit={e=>{e.preventDefault();setDone(true);}}><UI.Label htmlFor="demo-project">Projektname</UI.Label><UI.Input id="demo-project" value={value} onChange={e=>{setValue(e.target.value);setDone(false);}} required placeholder="Kundenportal"/><div className="demo-row"><UI.Checkbox id="demo-confirm"/><UI.Label htmlFor="demo-confirm">Belege geprüft</UI.Label></div><UI.Button type="submit">Eingabe prüfen</UI.Button><p role="status">{done?`«${value}» lokal geprüft.`:'Keine Daten werden versendet.'}</p></form></section>
 <section className="demo-panel"><h2>Dialog & Sheet</h2><div className="demo-row"><UI.Dialog><UI.DialogTrigger asChild><UI.Button variant="outline">Dialog öffnen</UI.Button></UI.DialogTrigger><UI.DialogContent><UI.DialogHeader><UI.DialogTitle>Projekt freigeben</UI.DialogTitle><UI.DialogDescription>Der Dialog übernimmt die aktive Brand. Escape schliesst und gibt den Fokus zurück.</UI.DialogDescription></UI.DialogHeader><UI.DialogFooter><UI.DialogClose asChild><UI.Button>Schliessen</UI.Button></UI.DialogClose></UI.DialogFooter></UI.DialogContent></UI.Dialog><UI.Sheet><UI.SheetTrigger asChild><UI.Button variant="outline">Detailpanel</UI.Button></UI.SheetTrigger><UI.SheetContent><UI.SheetHeader><UI.SheetTitle>Projektdetails</UI.SheetTitle><UI.SheetDescription>Ein seitliches Panel für Kontext und ergänzende Aktionen.</UI.SheetDescription></UI.SheetHeader></UI.SheetContent></UI.Sheet></div></section>
 <section className="demo-panel"><h2>Select & Dropdown Menu</h2><UI.Select defaultValue="draft"><UI.SelectTrigger aria-label="Projektstatus"><UI.SelectValue/></UI.SelectTrigger><UI.SelectContent><UI.SelectItem value="draft">Entwurf</UI.SelectItem><UI.SelectItem value="review">In Prüfung</UI.SelectItem><UI.SelectItem value="approved">Freigegeben</UI.SelectItem></UI.SelectContent></UI.Select><UI.DropdownMenu><UI.DropdownMenuTrigger asChild><UI.Button variant="outline">Aktionen</UI.Button></UI.DropdownMenuTrigger><UI.DropdownMenuContent><UI.DropdownMenuLabel>Projekt</UI.DropdownMenuLabel><UI.DropdownMenuItem onSelect={()=>toast('Export angefragt')}>Exportieren</UI.DropdownMenuItem><UI.DropdownMenuSeparator/><UI.DropdownMenuItem onSelect={()=>toast('Link kopieren ausgewählt')}>Link kopieren</UI.DropdownMenuItem></UI.DropdownMenuContent></UI.DropdownMenu></section>
 <section className="demo-panel"><h2>Tabs</h2><UI.Tabs defaultValue="preview"><UI.TabsList><UI.TabsTrigger value="preview">Vorschau</UI.TabsTrigger><UI.TabsTrigger value="code">Verwendung</UI.TabsTrigger></UI.TabsList><UI.TabsContent value="preview"><p>Mit Pfeiltasten zwischen Tabs wechseln.</p></UI.TabsContent><UI.TabsContent value="code"><code>{'<Tabs defaultValue="preview">…</Tabs>'}</code></UI.TabsContent></UI.Tabs></section>
 <section className="demo-panel"><h2>Popover & Tooltip</h2><div className="demo-row"><UI.Popover><UI.PopoverTrigger asChild><UI.Button variant="outline">Hinweise</UI.Button></UI.PopoverTrigger><UI.PopoverContent><strong>Kontext zur Aktion</strong><p>Kurze ergänzende Informationen, ohne die Seite zu verlassen.</p></UI.PopoverContent></UI.Popover><UI.TooltipProvider><UI.Tooltip><UI.TooltipTrigger asChild><UI.Button variant="ghost">Fokus oder Hover</UI.Button></UI.TooltipTrigger><UI.TooltipContent>Zusätzliche Erklärung</UI.TooltipContent></UI.Tooltip></UI.TooltipProvider></div></section>
 <section className="demo-panel"><h2>Card & Separator</h2><UI.Card><UI.CardHeader><UI.CardTitle>Projektübersicht</UI.CardTitle><UI.CardDescription>Zusammengehörige Informationen</UI.CardDescription></UI.CardHeader><UI.CardContent>Status: In Prüfung<UI.Separator className="my-4"/>Verantwortung: Projektleitung</UI.CardContent></UI.Card></section>
 <section className="demo-panel"><h2>Empty State & Skeleton</h2><UI.EmptyState icon={Inbox} title="Keine Einträge" description="Neue Projekte erscheinen hier."/><UI.Skeleton className="h-4 w-3/4 my-3"/><UI.Skeleton className="h-4 w-1/2"/></section>
 <section className="demo-panel"><h2>Command</h2><UI.Command><UI.CommandInput placeholder="Aktion suchen …"/><UI.CommandList><UI.CommandEmpty>Keine Aktion gefunden.</UI.CommandEmpty><UI.CommandGroup heading="Projekt"><UI.CommandItem onSelect={()=>toast('Projekt öffnen ausgewählt')}>Projekt öffnen</UI.CommandItem><UI.CommandItem onSelect={()=>toast('Einstellungen ausgewählt')}>Einstellungen</UI.CommandItem></UI.CommandGroup></UI.CommandList></UI.Command></section>
 <section className="demo-panel"><h2>Lightbox & Toaster</h2><p>Die Präsentationsgalerie zeigt alle 18 Muster vergrössert im Dialog.</p><a href="/praesentation">Zur Galerie</a><div className="demo-row"><UI.Button variant="outline" onClick={()=>toast.success('Änderung gespeichert')}>Erfolg</UI.Button><UI.Button variant="outline" onClick={()=>toast.error('Speichern fehlgeschlagen')}>Fehler</UI.Button></div></section>
 </div>;
}
