'use client';
import {useMemo,useState} from 'react';
import {AreaChart,Area,BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer} from 'recharts';
import {useReactTable,getCoreRowModel,getFilteredRowModel,getSortedRowModel,getPaginationRowModel,flexRender,type ColumnDef,type SortingState} from '@tanstack/react-table';
import {Button,Input} from '@rapold/framework-core';
import {useActiveBrand} from './framework-shell';
const series=[{month:'Jan',current:64,previous:59},{month:'Feb',current:72,previous:62},{month:'Mär',current:68,previous:66},{month:'Apr',current:81,previous:70},{month:'Mai',current:88,previous:75},{month:'Jun',current:96,previous:79}];
type Row={name:string;status:string;owner:string;coverage:number};
export default function DataShowcase({section}:{section:string}){
 const {brand,mode}=useActiveBrand();const c=brand.modes[mode]!;const [query,setQuery]=useState(''),[sorting,setSorting]=useState<SortingState>([]),[chart,setChart]=useState('bar');
 const data=useMemo<Row[]>(()=>Array.from({length:250},(_,i)=>({name:`Modul ${String(i+1).padStart(3,'0')}`,status:['Entwurf','In Prüfung','Freigegeben'][i%3],owner:['Produkt','Engineering','Betrieb'][i%3],coverage:60+i%41})),[]);
 const columns=useMemo<ColumnDef<Row>[]>(()=>[{accessorKey:'name',header:'Modul'},{accessorKey:'status',header:'Status'},{accessorKey:'owner',header:'Team'},{accessorKey:'coverage',header:'Abdeckung',cell:info=>`${info.getValue()} %`}],[]);
 const table=useReactTable({data,columns,state:{globalFilter:query,sorting},onGlobalFilterChange:setQuery,onSortingChange:setSorting,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),initialState:{pagination:{pageSize:10}}});
 const chartBase=<><CartesianGrid stroke={c.border} vertical={false}/><XAxis dataKey="month" tick={{fill:c['muted-foreground'],fontSize:12}} stroke={c.border}/><YAxis tick={{fill:c['muted-foreground'],fontSize:12}} stroke={c.border}/><Tooltip contentStyle={{background:c.popover,color:c['popover-foreground'],borderColor:c.border,fontFamily:brand.typography.family}}/><Legend/></>;
 if(section==='tables')return <><div className="filter-bar"><Input aria-label="Module filtern" placeholder="Name, Status oder Team …" value={query} onChange={e=>{setQuery(e.target.value);table.setPageIndex(0);}}/><span>{table.getFilteredRowModel().rows.length} Einträge</span></div><div className="data-table"><table><thead>{table.getHeaderGroups().map(g=><tr key={g.id}>{g.headers.map(h=><th key={h.id} aria-sort={h.column.getIsSorted()==='asc'?'ascending':h.column.getIsSorted()==='desc'?'descending':'none'}><button onClick={h.column.getToggleSortingHandler()}>{flexRender(h.column.columnDef.header,h.getContext())} {h.column.getIsSorted()==='asc'?'↑':h.column.getIsSorted()==='desc'?'↓':''}</button></th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr key={r.id}>{r.getVisibleCells().map(cell=><td key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table>{!table.getRowModel().rows.length&&<p>Keine passenden Module.</p>}</div><div className="pagination"><Button variant="outline" disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}>Zurück</Button><span>Seite {table.getState().pagination.pageIndex+1} / {Math.max(1,table.getPageCount())}</span><Button variant="outline" disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}>Weiter</Button></div><p className="muted">TanStack Table · 250 illustrative Beispieldatensätze · lokale Suche und Sortierung.</p></>;
 return <>{section==='dashboard'&&<div className="metrics">{[['96','Aktuelle Nutzung'],['79','Vorperiode'],['+21,5 %','Veränderung'],['6','Monate']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l} · Beispiel</span></div>)}</div>}<div className="filter-bar"><label>Darstellung <select value={chart} onChange={e=>setChart(e.target.value)}><option value="bar">Balken</option><option value="line">Linie</option><option value="area">Fläche</option></select></label><span>Illustrative Daten, keine Projektkennzahlen</span></div><div className="chart-surface" role="img" aria-label="Nutzung steigt im Beispiel von 64 im Januar auf 96 im Juni. Vorperiode: 59 bis 79."><ResponsiveContainer width="100%" height={340}>{chart==='bar'?<BarChart data={series}>{chartBase}<Bar dataKey="previous" name="Vorperiode" fill={c['muted-foreground']}/><Bar dataKey="current" name="Aktuell" fill={c.primary}/></BarChart>:chart==='line'?<LineChart data={series}>{chartBase}<Line type="monotone" dataKey="previous" name="Vorperiode" stroke={c['muted-foreground']} strokeDasharray="5 4"/><Line type="monotone" dataKey="current" name="Aktuell" stroke={c.primary} strokeWidth={2}/></LineChart>:<AreaChart data={series}>{chartBase}<Area dataKey="current" name="Aktuell" stroke={c.primary} fill={c.primary} fillOpacity={.12}/></AreaChart>}</ResponsiveContainer></div><div className="notice">Einordnung: Die aktuelle Serie liegt in allen sechs Beispielmonaten über der Vorperiode. Die Tabelle hält die exakten Werte zugänglich.</div><div className="data-table"><table><caption>Illustrative Beispieldaten</caption><thead><tr><th>Monat</th><th>Vorperiode</th><th>Aktuell</th></tr></thead><tbody>{series.map(r=><tr key={r.month}><td>{r.month}</td><td>{r.previous}</td><td>{r.current}</td></tr>)}</tbody></table></div></>;
}
