'use client';
import {useState} from 'react';
import {AreaChart,Area,BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer} from 'recharts';
import {useActiveBrand} from './framework-shell';
const series=[{month:'Jan',current:64,previous:59},{month:'Feb',current:72,previous:62},{month:'Mär',current:68,previous:66},{month:'Apr',current:81,previous:70},{month:'Mai',current:88,previous:75},{month:'Jun',current:96,previous:79}];
export default function DataShowcase({section}:{section:string}){
 const {brand,mode}=useActiveBrand();const c=brand.modes[mode]!;const [chart,setChart]=useState('bar');
 const chartBase=<><CartesianGrid stroke={c.border} vertical={false}/><XAxis dataKey="month" tick={{fill:c['muted-foreground'],fontSize:12}} stroke={c.border}/><YAxis tick={{fill:c['muted-foreground'],fontSize:12}} stroke={c.border}/><Tooltip contentStyle={{background:c.popover,color:c['popover-foreground'],borderColor:c.border,fontFamily:brand.typography.family}}/><Legend/></>;
 return <>{section==='dashboard'&&<div className="metrics">{[['96','Aktuelle Nutzung'],['79','Vorperiode'],['+21,5 %','Veränderung'],['6','Monate']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l} · Beispiel</span></div>)}</div>}<div className="filter-bar"><label>Darstellung <select value={chart} onChange={e=>setChart(e.target.value)}><option value="bar">Balken</option><option value="line">Linie</option><option value="area">Fläche</option></select></label><span>Illustrative Daten, keine Projektkennzahlen</span></div><div className="chart-surface" role="img" aria-label="Nutzung steigt im Beispiel von 64 im Januar auf 96 im Juni. Vorperiode: 59 bis 79."><ResponsiveContainer width="100%" height={340}>{chart==='bar'?<BarChart data={series}>{chartBase}<Bar dataKey="previous" name="Vorperiode" fill={c['muted-foreground']}/><Bar dataKey="current" name="Aktuell" fill={c.primary}/></BarChart>:chart==='line'?<LineChart data={series}>{chartBase}<Line type="monotone" dataKey="previous" name="Vorperiode" stroke={c['muted-foreground']} strokeDasharray="5 4"/><Line type="monotone" dataKey="current" name="Aktuell" stroke={c.primary} strokeWidth={2}/></LineChart>:<AreaChart data={series}>{chartBase}<Area dataKey="current" name="Aktuell" stroke={c.primary} fill={c.primary} fillOpacity={.12}/></AreaChart>}</ResponsiveContainer></div><div className="notice">Einordnung: Die aktuelle Serie liegt in allen sechs Beispielmonaten über der Vorperiode. Die Tabelle hält die exakten Werte zugänglich.</div><div className="data-table"><table><caption>Illustrative Beispieldaten</caption><thead><tr><th>Monat</th><th>Vorperiode</th><th>Aktuell</th></tr></thead><tbody>{series.map(r=><tr key={r.month}><td>{r.month}</td><td>{r.previous}</td><td>{r.current}</td></tr>)}</tbody></table></div></>;
}
