'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { createContext,useContext,useEffect,useState,type ReactNode } from 'react';
import { Search,PanelLeft,Sun,Moon,ChevronRight,Layers,ExternalLink } from 'lucide-react';
import { BrandProvider,CommandDialog,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem,Sheet,SheetContent,SheetTitle,SheetDescription,Toaster } from '@rapold/framework-core';
import { brands,neutral,toCssVariables,type Brand,type Mode } from '@rapold/framework-brands';
import { groups,pages,href } from './catalog';
const BrandContext=createContext<{brand:Brand;mode:Mode}>({brand:neutral,mode:'light'});
export const useActiveBrand=()=>useContext(BrandContext);
export default function FrameworkShell({children}:{children:ReactNode}) {
 const path=usePathname();const current=pages.find(p=>href(p.id)===path)??pages[0];
 const [brandId,setBrandId]=useState('neutral'),[requestedMode,setMode]=useState<Mode>('light'),[collapsed,setCollapsed]=useState(false),[closed,setClosed]=useState<string[]>([]),[search,setSearch]=useState(false),[mobile,setMobile]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('framework-preferences')??'{}');if(brands.some(b=>b.id===p.brand))setBrandId(p.brand);if(p.mode==='dark')setMode('dark');setCollapsed(p.collapsed===true);if(Array.isArray(p.closed))setClosed(p.closed.filter((x:unknown)=>typeof x==='string'));}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('framework-preferences',JSON.stringify({brand:brandId,mode:requestedMode,collapsed,closed}));}catch{}},[brandId,requestedMode,collapsed,closed,ready]);
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(v=>!v);}};document.addEventListener('keydown',handle);return()=>document.removeEventListener('keydown',handle);},[]);
 const brand=brands.find(b=>b.id===brandId)??neutral;const mode=requestedMode==='dark'&&brand.modes.dark?'dark':'light';
 const nav=(rail=false)=><>{groups.map(g=><div className="nav-group" key={g.title}><button className="nav-group-label" onClick={()=>setClosed(v=>v.includes(g.title)?v.filter(x=>x!==g.title):[...v,g.title])} aria-expanded={!closed.includes(g.title)} title={g.title}>{rail?<span>{g.title.slice(0,1)}</span>:<>{g.title}<ChevronRight size={13} className={closed.includes(g.title)?'':'rotate'}/></>}</button>{(!closed.includes(g.title)||rail)&&g.items.map(([id,title])=><Link key={id} href={href(id)} title={rail?title:undefined} aria-current={current.id===id?'page':undefined} onClick={()=>setMobile(false)} className="nav-link"><span className="nav-mark">{rail?title.slice(0,2):<span/>}</span>{!rail&&title}</Link>)}</div>)}</>;
 return <BrandProvider brand={{id:brand.id,mode,variables:toCssVariables(brand,mode)}}><BrandContext.Provider value={{brand,mode}}>
 <a className="skip" href="#main">Zum Inhalt</a><div className={`framework-app ${collapsed?'rail':''}`}>
 <aside className="sidebar"><Link href="/" className="identity"><Layers size={23}/>{!collapsed&&<span>Framework <small>0.2</small></span>}</Link><button className="search-trigger" onClick={()=>setSearch(true)} aria-label="Seiten durchsuchen"><Search size={16}/>{!collapsed&&<><span>Suchen</span><kbd>⌘ K</kbd></>}</button><nav aria-label="Hauptnavigation">{nav(collapsed)}</nav><div className="sidebar-foot">{collapsed?<Layers size={18}/>:<><strong>{brand.name}</strong><span>{brand.status==='draft'?'CI-Entwurf':'Neutrale Basis'}</span></>}</div></aside>
 <div className="workspace"><header className="toolbar"><button className="icon-button desktop-toggle" aria-label={collapsed?'Seitenleiste erweitern':'Seitenleiste einklappen'} onClick={()=>setCollapsed(v=>!v)}><PanelLeft size={18}/></button><button className="icon-button mobile-toggle" aria-label="Navigation öffnen" onClick={()=>setMobile(true)}><PanelLeft size={18}/></button><div className="breadcrumb"><span>{current.group}</span><ChevronRight size={14}/><strong>{current.title}</strong></div><div className="toolbar-controls"><label className="sr-only" htmlFor="brand-choice">Brand</label><select id="brand-choice" value={brandId} onChange={e=>setBrandId(e.target.value)}>{brands.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><button className="icon-button" aria-label={mode==='light'?'Dunkle Darstellung':'Helle Darstellung'} disabled={!brand.modes.dark} title={brand.modes.dark?'Darstellung wechseln':'Für diese Brand ist nur Hell definiert'} onClick={()=>setMode(mode==='light'?'dark':'light')}>{mode==='light'?<Moon size={17}/>:<Sun size={17}/>}</button><a className="icon-button" href="https://github.com/marcelrapold/design" aria-label="GitHub-Repository"><ExternalLink size={17}/></a></div></header>
 <main id="main" tabIndex={-1}>{children}</main><footer><span>Design Framework · {brand.name}</span><a href="/llms.txt">Agenten-Einstieg</a><a href="https://atlas.zvv.dev">Referenz: Atlas</a></footer></div></div>
 <Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="mobile-nav"><SheetTitle>Framework</SheetTitle><SheetDescription>Referenzseiten und Design-Verträge</SheetDescription><nav aria-label="Mobile Navigation">{nav()}</nav></SheetContent></Sheet>
 <CommandDialog open={search} onOpenChange={setSearch} title="Framework durchsuchen" description="Eine Referenzseite öffnen"><CommandInput placeholder="Tokens, Präsentation, Komponenten …"/><CommandList><CommandEmpty>Keine passende Seite.</CommandEmpty>{groups.map(g=><CommandGroup key={g.title} heading={g.title}>{g.items.map(([id,title])=><CommandItem key={id} value={title} onSelect={()=>{setSearch(false);window.location.assign(href(id));}}>{title}</CommandItem>)}</CommandGroup>)}</CommandList></CommandDialog><Toaster/>
 </BrandContext.Provider></BrandProvider>;
}
