'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { createContext,useContext,useEffect,useState,type ReactNode } from 'react';
import { Search,PanelLeft,Sun,Moon,ChevronRight,Layers,ExternalLink } from 'lucide-react';
import { BrandProvider,CommandDialog,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem,Sheet,SheetContent,SheetTitle,SheetDescription,Toaster } from '@rapold/framework-core';
import { brands,neutral,toCssVariables,type Brand,type Mode } from '@rapold/framework-brands';
import { groups,pages,href } from './catalog';
import {pageIcons,groupIcons} from './navigation-icons';
import {version} from '../../../../package.json';
const BrandContext=createContext<{brand:Brand;mode:Mode;setBrand:(id:string)=>void}>({brand:neutral,mode:'light',setBrand:()=>{}});
export const useActiveBrand=()=>useContext(BrandContext);
export default function FrameworkShell({children}:{children:ReactNode}) {
 const path=usePathname();const current=pages.find(p=>href(p.id)===path)??pages[0];
 const [brandId,setBrandId]=useState('neutral'),[requestedMode,setMode]=useState<Mode>('light'),[collapsed,setCollapsed]=useState(false),[closed,setClosed]=useState<string[]>([]),[search,setSearch]=useState(false),[mobile,setMobile]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('framework-preferences')??'{}');if(brands.some(b=>b.id===p.brand))setBrandId(p.brand);if(p.mode==='dark')setMode('dark');setCollapsed(p.collapsed===true);if(Array.isArray(p.closed))setClosed(p.closed.filter((x:unknown)=>typeof x==='string'));}catch{}const requested=new URLSearchParams(window.location.search).get('brand');if(brands.some(b=>b.id===requested))setBrandId(requested!);setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('framework-preferences',JSON.stringify({brand:brandId,mode:requestedMode,collapsed,closed}));}catch{}},[brandId,requestedMode,collapsed,closed,ready]);
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(v=>!v);}};document.addEventListener('keydown',handle);return()=>document.removeEventListener('keydown',handle);},[]);
 const selectBrand=(id:string)=>{if(!brands.some(b=>b.id===id))return;setBrandId(id);const url=new URL(window.location.href);url.searchParams.set('brand',id);window.history.replaceState(null,'',url);};
 const brand=brands.find(b=>b.id===brandId)??neutral;const mode=requestedMode==='dark'&&brand.modes.dark?'dark':'light';
 const nav=(rail=false)=><>{groups.map(g=>{const GroupIcon=groupIcons[g.title]??Layers;return <div className="nav-group" key={g.title}>{rail?<div className="rail-group" title={g.title}><GroupIcon size={14} aria-hidden="true"/><span className="sr-only">{g.title}</span></div>:<button className="nav-group-label" onClick={()=>setClosed(v=>v.includes(g.title)?v.filter(x=>x!==g.title):[...v,g.title])} aria-expanded={!closed.includes(g.title)}><GroupIcon size={14} aria-hidden="true"/><span>{g.title}</span><ChevronRight size={13} className={closed.includes(g.title)?'':'rotate'}/></button>}{(!closed.includes(g.title)||rail)&&g.items.map(([id,title])=>{const Icon=pageIcons[id]??Layers;return <Link key={id} href={href(id)} prefetch={false} title={rail?title:undefined} aria-label={rail?title:undefined} aria-current={current.id===id?'page':undefined} onClick={()=>setMobile(false)} className="nav-link"><Icon size={16} aria-hidden="true"/>{!rail&&<span>{title}</span>}</Link>;})}</div>;})}</>;
 return <BrandProvider brand={{id:brand.id,mode,variables:toCssVariables(brand,mode)}}><BrandContext.Provider value={{brand,mode,setBrand:selectBrand}}>
 <a className="skip" href="#main">Zum Inhalt</a><div className={`framework-app ${collapsed?'rail':''}`}>
 <aside className="sidebar"><Link href="/" className={`identity ${brand.assets?.logo&&!collapsed?'identity-brand':''}`} aria-label={`${brand.name} · Startseite`}>{brand.assets?.logo&&!collapsed?<img src={`/${brand.assets.logo.path}`} width={142} height={24} alt={`${brand.name}-Logo`}/>:<><Layers size={23}/>{!collapsed&&<span>Framework <small>{version}</small></span>}</>}</Link><button className="search-trigger" onClick={()=>setSearch(true)} aria-label="Seiten durchsuchen"><Search size={16}/>{!collapsed&&<><span>Suchen</span><kbd>⌘ K</kbd></>}</button><nav aria-label="Hauptnavigation">{nav(collapsed)}</nav><div className="sidebar-foot">{collapsed?<Layers size={18}/>:<><strong>{brand.name}</strong><span>{brand.status==='draft'?'CI-Entwurf':'Neutrale Basis'}</span></>}</div></aside>
 <div className="workspace"><header className="toolbar"><button className="icon-button desktop-toggle" aria-label={collapsed?'Seitenleiste erweitern':'Seitenleiste einklappen'} onClick={()=>setCollapsed(v=>!v)}><PanelLeft size={18}/></button><button className="icon-button mobile-toggle" aria-label="Navigation öffnen" onClick={()=>setMobile(true)}><PanelLeft size={18}/></button><div className="breadcrumb"><span>{current.group}</span><ChevronRight size={14}/><strong>{current.title}</strong></div><div className="toolbar-controls"><label className="sr-only" htmlFor="brand-choice">Theme</label><select id="brand-choice" value={brandId} onChange={e=>selectBrand(e.target.value)}>{brands.map(b=><option value={b.id} key={b.id}>{b.id==='neutral'?'Default':b.name}</option>)}</select><button className="icon-button" aria-label={mode==='light'?'Dunkle Darstellung':'Helle Darstellung'} disabled={!brand.modes.dark} title={brand.modes.dark?'Darstellung wechseln':'Für diese Brand ist nur Hell definiert'} onClick={()=>setMode(mode==='light'?'dark':'light')}>{mode==='light'?<Moon size={17}/>:<Sun size={17}/>}</button><a className="icon-button" href="https://github.com/marcelrapold/design" aria-label="GitHub-Repository"><ExternalLink size={17}/></a></div></header>
 <main id="main" tabIndex={-1}>{children}</main><footer><span>Design Framework · {brand.name}</span><a href={`/brands/${brand.id}/llms.txt`}>Agenten-Einstieg</a><a href="https://atlas.zvv.dev">Referenz: Atlas</a></footer></div></div>
 <Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="mobile-nav"><SheetTitle>{brand.assets?.logo?<span className="mobile-brand-logo"><img src={`/${brand.assets.logo.path}`} width={142} height={24} alt={`${brand.name}-Logo`}/></span>:brand.name}</SheetTitle><SheetDescription>Referenzseiten und Design-Verträge</SheetDescription><nav aria-label="Mobile Navigation">{nav()}</nav></SheetContent></Sheet>
 <CommandDialog open={search} onOpenChange={setSearch} title="Framework durchsuchen" description="Eine Referenzseite öffnen"><CommandInput placeholder="Tokens, Präsentation, Komponenten …"/><CommandList><CommandEmpty>Keine passende Seite.</CommandEmpty>{groups.map(g=><CommandGroup key={g.title} heading={g.title}>{g.items.map(([id,title])=><CommandItem key={id} value={title} onSelect={()=>{setSearch(false);window.location.assign(href(id));}}><span className="command-icon">{(()=>{const Icon=pageIcons[id]??Layers;return <Icon size={16} aria-hidden="true"/>;})()}</span>{title}</CommandItem>)}</CommandGroup>)}</CommandList></CommandDialog><Toaster/>
 </BrandContext.Provider></BrandProvider>;
}
