'use client';
import {useMemo,useState,type ComponentType} from 'react';
import * as Lucide from 'lucide-react';
import {Input,Button,Dialog,DialogContent,DialogTitle,DialogDescription} from '@rapold/framework-core';
const icons=Lucide.icons as Record<string,ComponentType<Lucide.LucideProps>>;
const names=Object.keys(icons).filter(n=>!n.endsWith('Icon')&&!n.startsWith('Lucide')).sort();
export default function IconGallery(){
 const [query,setQuery]=useState(''),[limit,setLimit]=useState(120),[selected,setSelected]=useState<string|null>(null),[message,setMessage]=useState('');
 const filtered=useMemo(()=>names.filter(n=>n.toLowerCase().includes(query.trim().toLowerCase())),[query]);const Selected=selected?icons[selected]:null;
 const copy=async()=>{try{await navigator.clipboard.writeText(`import { ${selected} } from 'lucide-react';\n\n<${selected} size={20} strokeWidth={1.5} aria-hidden="true" />`);setMessage('Import und Verwendung kopiert.');}catch{setMessage('Bitte den Code unten markieren und kopieren.');}};
 return <><div className="notice">Lucide ist der neutrale Icon-Satz aus Atlas. {names.length} Icons. 16 / 20 / 24 px, Strichstärke 1,5. Originalgeometrie und ISC-Lizenz bleiben erhalten.</div><div className="filter-bar"><Input aria-label="Icon suchen" type="search" value={query} placeholder="Icon suchen: arrow, chart, folder, check …" onChange={e=>{setQuery(e.target.value);setLimit(120);}}/><span>{filtered.length} Treffer</span></div><div className="icon-grid">{filtered.slice(0,limit).map(name=>{const Icon=icons[name];return <button key={name} title={name} onClick={()=>{setSelected(name);setMessage('');}}><Icon size={24} strokeWidth={1.5} aria-hidden="true"/><span>{name}</span></button>;})}</div>{!filtered.length&&<p>Keine Icons gefunden.</p>}{filtered.length>limit&&<Button variant="outline" onClick={()=>setLimit(n=>n+120)}>Weitere Icons laden</Button>}<Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent><DialogTitle>{selected}</DialogTitle><DialogDescription>Neutraler Interface-Baustein aus Lucide</DialogDescription>{Selected&&<div className="demo-row"><Selected size={16} strokeWidth={1.5}/><Selected size={20} strokeWidth={1.5}/><Selected size={24} strokeWidth={1.5}/><Selected size={64} strokeWidth={1.5}/></div>}<pre>{`import { ${selected} } from 'lucide-react';\n<${selected} size={20} strokeWidth={1.5} />`}</pre><div className="demo-row"><Button onClick={copy}>Code kopieren</Button><a href={`/icons/${selected}.svg`} download>SVG herunterladen</a></div><p role="status">{message}</p></DialogContent></Dialog><section className="doc-section"><h2>Verwendungsregeln</h2><p>Beschriftete Aktionen verwenden ein dekoratives Icon mit aria-hidden. Reine Icon-Buttons benötigen einen verständlichen zugänglichen Namen. Keine fremden Markenlogos im neutralen Satz. Corporate-Icons bleiben Teil des jeweiligen Brand-Pakets.</p><a href="/icons/index.json">Vollständiges Icon-Inventar als JSON</a> · <a href="/icons/LICENSE.txt">Lucide-Lizenz</a></section></>;
}
