'use client';
import {useState,useRef,useEffect} from 'react';
import {Button,Input,Label,EmptyState,Skeleton,Lightbox} from '@rapold/framework-core';
import {Inbox,Search,TriangleAlert,ArrowRight,Copy} from 'lucide-react';
import {toast} from 'sonner';
import {useActiveBrand} from './framework-shell';
const defaultDiagram='flowchart LR\n  Project[Projektinhalt] --> Evidence[Belegte Aussagen]\n  Evidence --> Story[Entscheidungslogik]\n  Brand[Brand-Vertrag] --> Deck[Management-Deck]\n  Story --> Deck';
function download(text:string,name:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export default function PatternShowcase({section}:{section:string}){
 const {brand,mode}=useActiveBrand();const [message,setMessage]=useState(''),[title,setTitle]=useState(''),[notes,setNotes]=useState(''),[step,setStep]=useState(0),[code,setCode]=useState(defaultDiagram),[rendered,setRendered]=useState(''),[error,setError]=useState(''),[idea,setIdea]=useState('Projekt analysieren und dem Management eine Entscheidung ermöglichen.'),[format,setFormat]=useState('Präsentation'),[tree,setTree]=useState('Geschäftsleitung\n  Produkt\n    Design\n    Entwicklung\n  Betrieb\n    Service\n    Qualität');
 const [diagramRequest,setDiagramRequest]=useState<{code:string;version:number}|null>(null);
 const renderId=useRef(0);
 const diagramColors=brand.modes[mode]??brand.modes.light;
 const {muted:diagramFill,foreground:diagramText,primary:diagramLine}=diagramColors;
 const diagramFont=brand.typography.family;
 const renderDiagram=()=>setDiagramRequest(previous=>({code,version:(previous?.version??0)+1}));
 useEffect(()=>{
  if(!diagramRequest)return;
  let cancelled=false;const id=++renderId.current;
  const render=async()=>{try{
   const {default:mermaid}=await import('mermaid');
   if(cancelled)return;
   mermaid.initialize({startOnLoad:false,securityLevel:'strict',maxTextSize:30000,theme:'base',themeVariables:{primaryColor:diagramFill,primaryTextColor:diagramText,primaryBorderColor:diagramLine,lineColor:diagramLine,fontFamily:diagramFont}});
   const {svg}=await mermaid.render(`framework-diagram-${id}`,diagramRequest.code);
   if(!cancelled){setRendered(svg);setError('');}
  }catch(e){if(!cancelled){setRendered('');setError(e instanceof Error?e.message:'Diagramm konnte nicht gerendert werden.');}}};
  void render();return ()=>{cancelled=true;};
 },[diagramRequest,diagramFill,diagramText,diagramLine,diagramFont]);
 const prompt=`AUFTRAG\n${idea}\n\nERGEBNIS\n${format} im ${brand.name}-CI.\n\nVERBINDLICHE QUELLEN\nhttps://design.rapold.io/llms.txt\nhttps://design.rapold.io/brands/${brand.id}/brand.json\nhttps://design.rapold.io/brands/${brand.id}/presentation.json\nhttps://design.rapold.io/contracts/presentation-logic.md\n\nVORGEHEN\nRepository und Commit erfassen. Aussagen mit Pfad belegen. Fakten, Annahmen und offene Fragen trennen. Sektionsgliederung auf die Entscheidungsfrage ausrichten. Erst Quelle, dann Kennzahl. Jede Sektion mit Entscheid, Auftrag oder Klärungspunkt abschliessen. Alle Layouts und Tokenwerte aus den Verträgen lesen. Brand-Assets unverändert übernehmen.\n\nABNAHME\nDeck-Inhalt mit scripts/validate-deck.mjs prüfen, anschliessend jede Folie rendern und auf Überlauf, Kontrast und Evidenz prüfen. Keine unbekannten Daten erfinden.`;
 const copy=async(v:string)=>{try{await navigator.clipboard.writeText(v);setMessage('Kopiert.');}catch{setMessage('Text direkt markieren und kopieren.');}};
 if(section==='toasts')return <><div className="demo-panel"><h2>Benachrichtigungen</h2><div className="demo-row"><Button onClick={()=>toast.success('Änderungen gespeichert')}>Erfolg</Button><Button variant="outline" onClick={()=>toast.error('Speichern fehlgeschlagen',{description:'Bitte die Eingaben prüfen.'})}>Fehler</Button><Button variant="outline" onClick={()=>toast.info('Neue Version verfügbar')}>Information</Button><Button variant="outline" onClick={()=>toast.warning('Eine Angabe fehlt')}>Warnung</Button><Button variant="outline" onClick={()=>toast.promise(Promise.resolve('fertig'),{loading:'Wird geprüft …',success:'Prüfung abgeschlossen',error:'Prüfung fehlgeschlagen'})}>Promise</Button></div><p>Kurze Bestätigung nach einer Aktion. Dauerhafte Fehler bleiben zusätzlich am betroffenen Feld sichtbar.</p></div></>;
 if(section==='empty-states')return <div className="demo-grid"><div className="demo-panel"><EmptyState icon={Inbox} title="Noch keine Projekte" description="Ein erstes Projekt anlegen, um zu starten."/><Button onClick={()=>setMessage('Lokale Beispielaktion ausgelöst.')}>Projekt anlegen</Button></div><div className="demo-panel"><EmptyState icon={Search} title="Keine Treffer" description="Andere Begriffe oder weniger Filter verwenden."/><Button variant="outline" onClick={()=>setMessage('Beispielfilter zurückgesetzt.')}>Filter zurücksetzen</Button></div><div className="demo-panel"><EmptyState icon={TriangleAlert} title="Daten nicht verfügbar" description="Die Verbindung konnte nicht hergestellt werden."/><Button variant="outline" onClick={()=>setMessage('Erneute Prüfung simuliert.')}>Erneut prüfen</Button></div><p role="status">{message}</p></div>;
 if(section==='skeletons')return <div className="demo-grid">{['Profil','Karte','Kennzahlen','Tabelle'].map(name=><div className="demo-panel" key={name} aria-busy="true" aria-label={`${name} wird geladen`}><h2>{name}</h2>{name==='Profil'&&<Skeleton className="size-12 rounded-full mb-4"/>}{Array.from({length:name==='Tabelle'?6:3},(_,i)=><Skeleton className={`h-5 my-3 ${i%2?'w-2/3':'w-full'}`} key={i}/>)}</div>)}</div>;
 if(section==='lightbox')return <><p className="muted">Das importierte Atlas-Modul übernimmt Fokusfalle, Escape, Rückkehr zum Auslöser und Scrollsperre.</p><Lightbox label="Layout-Raster"><div className="demo-panel"><h2>Zwölf Spalten</h2><div className="grid-demo">{Array.from({length:12},(_,i)=><div key={i}>{i+1}</div>)}</div></div></Lightbox></>;
 if(section==='mermaid')return <><div className="notice">Lokaler Mermaid-Renderer, Sicherheitseinstellung strict. Keine externen Daten werden geladen.</div><Label htmlFor="diagram-code">Diagrammdefinition</Label><textarea id="diagram-code" className="code-editor" value={code} onChange={e=>setCode(e.target.value)}/><div className="demo-row"><Button onClick={renderDiagram}>Diagramm rendern</Button><Button variant="outline" disabled={!rendered} onClick={()=>download(rendered,'diagram.svg','image/svg+xml')}>SVG exportieren</Button></div>{error&&<pre role="alert">{error}</pre>}<div className="diagram-output" dangerouslySetInnerHTML={{__html:rendered}}/>{!rendered&&<p>Definition bearbeiten und rendern.</p>}</>;
 if(section==='organigramm'){const rows=tree.split('\n').filter(l=>l.trim());return <><p>Einrückung bestimmt die Hierarchie. Ausschliesslich lokale Beispieldaten.</p><textarea className="code-editor" aria-label="Organigramm bearbeiten" value={tree} onChange={e=>setTree(e.target.value)}/><div className="org-tree">{rows.map((line,i)=>{const depth=Math.floor((line.length-line.trimStart().length)/2);return <div key={i} style={{marginLeft:`${Math.min(depth,6)*28}px`}}><span>{line.trim()}</span></div>;})}</div><Button variant="outline" onClick={()=>download(JSON.stringify(rows.map(l=>({label:l.trim(),level:Math.floor((l.length-l.trimStart().length)/2)})),null,2),'organigramm.json','application/json')}>Struktur exportieren</Button></>};
 if(section==='forms')return <div className="demo-panel"><h2>Projekt erfassen</h2><form onSubmit={e=>{e.preventDefault();if(title.trim().length<3){setError('Der Projektname braucht mindestens drei Zeichen.');return;}setError('');setMessage(`«${title}» lokal geprüft. Keine Daten versendet.`);}}><Label htmlFor="form-title">Projektname</Label><Input id="form-title" value={title} onChange={e=>setTitle(e.target.value)} required minLength={3} aria-invalid={!!error} aria-describedby="form-error"/><p id="form-error" role="alert">{error}</p><Label htmlFor="form-notes">Ziel und Nutzen</Label><textarea id="form-notes" value={notes} onChange={e=>setNotes(e.target.value)} required className="code-editor"/><Button type="submit">Prüfen</Button><p role="status">{message}</p></form></div>;
 if(section==='auth-flow')return <><div className="notice">Ablaufmuster ohne angeschlossenen Identitätsanbieter.</div><div className="step-list">{['E-Mail erfassen','Zulässigkeit serverseitig prüfen','Zeitlich begrenzten Link versenden','Token einmalig einlösen','Sitzung und Berechtigung prüfen'].map((s,i)=><div key={s} className={i===step?'active':''}><span>{i+1}</span>{s}</div>)}</div><div className="demo-row"><Button disabled={step===0} variant="outline" onClick={()=>setStep(s=>s-1)}>Zurück</Button><Button disabled={step===4} onClick={()=>setStep(s=>s+1)}>Nächster Schritt</Button></div><p>Öffentliche Antworten vermeiden die Preisgabe existierender Konten. Tokenablauf, Rate-Limits, Session-Prüfung und serverseitige Autorisierung gehören in die Anwendung.</p></>;
 if(section==='login-pattern')return <><div className="notice">Design-Vorschau. Dieses Formular meldet niemanden an.</div><div className="login-example"><div><strong>{brand.name}</strong><h2>Projektarbeitsraum</h2><p>Zugang zu gemeinsamen Projekten und Entscheidungen.</p></div><form onSubmit={e=>{e.preventDefault();setMessage('Vorschau: Hier würde die Anwendung den Anmeldeprozess starten.');}}><h2>Anmelden</h2><Label htmlFor="login-email">Geschäftliche E-Mail</Label><Input id="login-email" type="email" required placeholder="name@firma.ch"/><Button type="submit">Anmeldelink anfordern</Button><p role="status">{message}</p></form><div><h3>Hinweise zum Zugang</h3><p>Berechtigungen verwaltet die Organisation. Der Framework-Core kennt keine Konten oder Zugangsdaten.</p></div></div></>;
 if(section==='mail-templates'){const c=brand.modes.light;const html=`<!doctype html><html lang="de"><body style="font-family:Arial,sans-serif;background:${c.background};padding:28px;color:${c.foreground}"><table role="presentation" style="max-width:600px;margin:auto;background:${c.card};padding:32px;width:100%"><tr><td><h2>${brand.name}</h2><h1 style="font-size:24px">Dein Projekt steht zur Prüfung bereit</h1><p>Die Projektübersicht wurde aktualisiert. Prüfe die belegten Aussagen und ergänze offene Punkte.</p><p style="padding:14px;background:${c.primary};color:${c['primary-foreground']}">Projekt öffnen · Beispielaktion</p><hr/><p style="font-size:12px">Illustrative Vorlage · kein Versand</p></td></tr></table></body></html>`;return <><div className="notice">HTML-Mail-Vorlage in der aktiven Brand. Vorschau ohne externe Inhalte oder Versand.</div><iframe title="Mail-Vorschau" srcDoc={html} sandbox="" className="mail-preview"/><Button onClick={()=>download(html,'mail-template.html','text/html')}>HTML herunterladen</Button></>};
 if(section==='prompt-compiler'||section==='prompt-vorlagen')return <><Label htmlFor="prompt-idea">Auftrag</Label><textarea id="prompt-idea" className="code-editor" value={idea} onChange={e=>setIdea(e.target.value)}/><label>Ergebnisformat <select value={format} onChange={e=>setFormat(e.target.value)}><option>Präsentation</option><option>Interface</option><option>Management-Briefing</option></select></label><pre>{prompt}</pre><Button onClick={()=>copy(prompt)}><Copy size={16}/>Auftrag kopieren</Button><p role="status">{message}</p><p className="muted">Deterministischer Compiler für einen vollständigen Agenten-Auftrag. Keine gehostete Modellabfrage.</p></>;
 if(section==='health-status')return <><div className="notice">Diese Referenz zeigt Build-Informationen. Sie behauptet keine Verfügbarkeit externer Dienste.</div><div className="token-table"><div><strong>Referenz</strong><span>Statischer Export</span></div><div><strong>Brand</strong><span>{brand.name} / {mode}</span></div><div><strong>Tokenquelle</strong><span>Versionierter Brand-Vertrag</span></div><div><strong>Externe Dienste</strong><span>Nicht angeschlossen</span></div></div><div className="download-row"><a href="/build-info.json">Build-Informationen als JSON</a><a href="https://github.com/marcelrapold/design/actions">CI-Läufe</a></div></>;
 if(section==='marketing-hero')return <><div className="notice">Neutrales Muster für einen Projektauftritt. Wortwahl und Assets stammen aus dem Projekt und der aktiven Brand.</div><section className="project-hero"><p className="eyebrow">Projekt / {brand.name}</p><h2>Gemeinsamer Arbeitsraum</h2><p>Projektstand prüfen, Belege nachvollziehen und Entscheidungen vorbereiten.</p><Button onClick={()=>setMessage('Beispielaktion ausgelöst.')}>Projekt öffnen <ArrowRight size={16}/></Button><p role="status">{message}</p></section></>;
 return null;
}
