'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,Copy,Download,FileCode,FileJson,ImageIcon,Presentation,TriangleAlert} from 'lucide-react';
import {Button,Input,Dialog,DialogContent,DialogTitle,DialogDescription} from '@rapold/framework-core';
import {presentationTheme,slides,presets} from '../../../../packages/brands/src/presentation.mjs';
import {useActiveBrand} from './framework-shell';
const rules=[['Quellen vor Kennzahlen','Die Quellenfolie erklärt Herkunft und Umfang. Jede Kennzahl trägt Zeitraum, Quelle und Vergleichsanker.'],['Werte direkt beschriften','Balken tragen Werte am Ende. Diagrammserien erhalten Namen; Einheiten und Vergleichsperiode bleiben sichtbar.'],['Alarmfarben gezielt einsetzen','Negative Veränderungen bleiben neutral. Ein echter Alarm erhält signal; Ausnahmen bei KPI-Deltas brauchen eine eindeutige Bedeutung.'],['Sektionen abschliessen','Jede Sektion endet mit einem Entscheid, einem Auftrag oder einer ausdrücklich offenen Frage. Zuständigkeit und Termin gehören zu Entscheiden und Aufträgen.'],['Evidenz und Deutung trennen','Jede Visualisierung erhält eine räumlich getrennte Einordnung. Fakten, Ableitungen und offene Fragen sind erkennbar.'],['Dieselben Regeln im Anhang','Quellen, Typografie, Zahlenformat und Farbsemantik gelten für jede Folie, einschliesslich des Anhangs.']];
const steps=[['Vertrag lesen','Brand, Folienrezepte und Inhaltsregeln bestimmen den Aufbau.'],['Projekt verstehen','Anlass, Publikum und Entscheidungsfrage klären. Aussagen am Repository belegen.'],['Deck erzeugen','Das geprüfte Inhaltsmodell füllt die vermessenen Atlas-Layouts.'],['Ergebnis prüfen','PowerPoint und Quellenmanifest prüfen. Jede Folie rendern und visuell abnehmen.']];
const faqs=[['Brauche ich PowerPoint?','Zum Erzeugen nicht. Die editierbare PPTX lässt sich anschliessend in einer kompatiblen Präsentationsanwendung öffnen.'],['Woher kommt die Gestaltung?','Raster und Rezepte stammen aus Atlas. Farben, Schriften und Original-Assets liefert die aktive Brand.'],['Was muss ich installieren?','Ein ausführender Agent braucht Repo-Zugang und Node.js. Der optionale PDF-Export und das Erzeugen der Referenzbilder verwenden LibreOffice und Poppler.'],['Was passiert bei zu viel Inhalt?','Der Export meldet die überschrittene Kapazität. Der Inhalt muss auf weitere Folien verteilt werden. Er setzt keine Beispieldaten ein.'],['Sind Bilder und Logos dabei?','Das gelieferte Goldbach-Logo ist enthalten. Für fotografische Layouts braucht das Projekt ein eigenes freigegebenes Motiv.'],['Ist die CI freigegeben?','Goldbach bleibt ein dokumentierter CI-Entwurf. Eine technische Prüfung ersetzt die Freigabe durch die Brand-Verantwortlichen nicht.']];
function RenderedSlide({brand,id,large=false}:{brand:string;id:string;large?:boolean}){return <img className="rendered-slide" src={`/brands/${brand}/reference/${id}.png`} width={1280} height={720} alt={`Gerenderte Musterfolie: ${slides.find(s=>s.id===id)?.titel}`} loading={large?'eager':'lazy'}/>;}
export default function PresentationPage(){
 const {brand}=useActiveBrand(),deck=presentationTheme(brand);
 const [repository,setRepository]=useState('owner/repo'),[preset,setPreset]=useState(presets[0].id),[selected,setSelected]=useState<string|null>(null),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState('');
 const selectedType=slides.find(s=>s.id===selected),base=`/brands/${brand.id}`,download=`${base}/decks`;
 const move=(delta:number)=>setSelected(id=>slides[(slides.findIndex(s=>s.id===id)+delta+slides.length)%slides.length].id);
 useEffect(()=>{if(!selected)return;const key=(event:KeyboardEvent)=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();setSelected(id=>slides[(slides.findIndex(s=>s.id===id)+(event.key==='ArrowRight'?1:-1)+slides.length)%slides.length].id);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[selected]);
 const prompt=`Analysiere das Repository ${repository||'owner/repo'}. Erstelle eine Management-Präsentation mit https://design.rapold.io im ${brand.name}-CI. Lies /praesentation/llms.txt, /brands/${brand.id}/presentation.json und /contracts/presentation-logic.md. Nutze das Preset ${preset}, soweit es zur belegten Substanz passt. Belege Aussagen mit Commit und Dateipfad. Erzeuge ein Inhaltsmodell nach /praesentation/project-input.schema.json. Exportiere es mit npm run deck:export -- deck.json --out ./ergebnis --repo-dir ./projekt --pdf. Liefere die editierbare PPTX, PDF und sources.json. Prüfe jede gerenderte Folie.`;
 const copy=async()=>{try{await navigator.clipboard.writeText(prompt);setCopied(true);setCopyError('');}catch{setCopied(false);setCopyError('Kopieren nicht verfügbar. Auftrag direkt markieren und kopieren.');}};
 const zones=[{name:'Botschafts-Titel · 30 pt',...deck.layout.titel},{name:'Logo',...deck.layout.logo},{name:'Lead · Zeitraum und Quelle',...deck.layout.lead,h:deck.layout.lead.h1zeilig},{name:'Inhaltszone · 32 cm Nutzbreite',x:deck.layout.randLR,y:deck.layout.inhalt.yStart,w:deck.layout.nutzbreite,h:deck.layout.inhalt.yEnde-deck.layout.inhalt.yStart},{name:'Quelle · 8 pt',...deck.layout.quellzeile}];
 return <><div className="page-heading"><p className="eyebrow">Agenten / {brand.name}</p><h1>Präsentation</h1><p>Der Präsentationsbaukasten auf Basis von Atlas. Vermessene Layouts, ausführbare Folienrezepte und dieselbe Brand für Website und PowerPoint.</p><div className="page-meta"><span className="status-label">{brand.status==='draft'?'CI-Entwurf':'Framework-Standard'}</span><a href="/contracts/presentation-logic.md"><BookOpen size={14}/>Inhaltsregeln</a></div></div>
 <nav className="page-anchors" aria-label="Auf dieser Seite">{[["auftrag","Auftrag"],["downloads","Vorlagen"],["raster","Raster"],["deckfarben","Farben"],["decktypografie","Typografie"],["folientypen","Folientypen"],["presets","Presets"],["grundregeln","Regeln"]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
 <section className="deck-intro" id="auftrag"><p className="eyebrow">Vom Projekt zur Präsentation</p><h2>Ein Projektauftrag. Eine bearbeitbare Präsentation.</h2><p>Dein Agent analysiert das Repository und baut daraus ein Management-Deck. Die Referenz liefert die Regeln, die Layouts und den Export.</p><div className="deck-facts"><div><strong>{slides.length}</strong><span>Folientypen</span></div><div><strong>{presets.length}</strong><span>Deck-Presets</span></div><div><strong>{Object.keys(deck.typography.scale).length}</strong><span>Typorollen</span></div><div><strong>16:9</strong><span>33,867 × 19,05 cm</span></div></div><div className="builder-controls"><label>Repository<Input value={repository} onChange={e=>setRepository(e.target.value)}/></label><label>Anlass<select value={preset} onChange={e=>setPreset(e.target.value)}>{presets.map(p=><option value={p.id} key={p.id}>{p.titel}</option>)}</select></label></div><pre>{prompt}</pre><Button onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Kopiert':'Auftrag kopieren'}</Button>{copyError&&<p role="status">{copyError}</p>}<p className="muted">Der Auftrag wird von deinem Agenten ausgeführt. Diese Referenz lädt keine privaten Repositories.</p></section>
 <section className="doc-section"><h2>Was danach passiert</h2><ol className="deck-steps">{steps.map(([title,body],i)=><li key={title}><span>{i+1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol><div className="deck-faq">{faqs.map(([question,answer])=><div key={question}><h3>{question}</h3><p>{answer}</p></div>)}</div></section>
 <section className="doc-section" id="downloads"><h2>Vorlagen und Verträge</h2><div className="download-row"><a href={`${download}/muster-deck.pptx`} download><Download size={15}/> Muster-Deck · PPTX</a><a href={`${base}/reference/muster-deck.pdf`} download>PDF</a><a href={`${download}/${preset}.pptx`} download>Gewähltes Preset · PPTX</a><a href={`${base}/presentation.json`}><FileJson size={15}/> Tokens & Rezepte</a><a href="/praesentation/llms.txt">Agenten-Vertrag</a><a href="/praesentation/project-input.schema.json">Projektdeck-Schema</a><a href="/praesentation/framework-review.json">Belegtes Projektbeispiel</a></div></section>
 <section className="doc-section"><h2>Die Vorschau stammt aus der PowerPoint</h2><p>Die Galerie zeigt gerenderte Folien aus den herunterladbaren Dateien. Ein Prüfschritt verhindert, dass geänderte Layouts mit veralteten Vorschaubildern veröffentlicht werden.</p><ol className="deck-pipeline">{[[FileJson,'Brand & Tokens','Geometrie, Farben, Schrift'],[FileCode,'Folienrezepte','Strukturierte Inhalte'],[Presentation,'PowerPoint','Editierbare Objekte'],[ImageIcon,'PDF & Folienbilder','Aus der exportierten Datei'],[BookOpen,'Diese Referenz','Galerie und Anleitung']].map(([Icon,title,body]:any)=><li key={title}><Icon size={19}/><strong>{title}</strong><span>{body}</span></li>)}</ol><a className="muted" href="/presentation-reference.json">Herkunft und Prüfsummen der Referenzbilder</a></section>
 <section className="doc-section" id="raster"><h2>Das Fünf-Zonen-Gerüst</h2><p>Die Positionen werden aus den Deck-Tokens berechnet. Titel, Lead, Evidenz, Fusslinie und Quelle bleiben über alle Arbeitsfolien konsistent.</p><div className="zone-diagram">{zones.map(z=><div key={z.name} style={{left:`${z.x/33.867*100}%`,top:`${z.y/19.05*100}%`,width:`${z.w/33.867*100}%`,height:`${z.h/19.05*100}%`}}>{z.name}</div>)}</div></section>
 <section className="doc-section" id="deckfarben"><h2>Deck-Farben und ihre Bedeutung</h2><div className="token-grid">{[['primary','Aktuelle Aussage'],['chart-previous','Vorperiode und Vergleich'],['surface-info','Hervorgehobene Einordnung'],['surface-neutral','Neutrale Evidenz'],['text','Primärer Text'],['text-secondary','Begleitender Text'],['warning','Klärungsbedarf'],['signal','Echter Alarm'],['success','Positiver Status'],['border','Trennlinien'],['surface','Folienfläche'],['on-color','Text auf Primary']].map(([role,label])=><div className="token-card" key={role}><div className="swatch" style={{background:deck.colors[role]}}/><code>{role}</code><span>{deck.colors[role]}</span><small>{label}</small></div>)}</div></section>
 <section className="doc-section" id="decktypografie"><h2>Typografie · {deck.typography.family}</h2><p>{Object.keys(deck.typography.scale).length} Rollen aus dem vermessenen Atlas-Raster. Die Brand bestimmt Schriftfamilie und Gewichte.</p><div className="deck-type-scale">{Object.entries(deck.typography.scale).map(([role,value]:[string,any])=><div key={role}><code>{role}<small>{value.pt} pt</small></code><span style={{fontSize:Math.min(value.pt*1.15,38),fontWeight:value.weight==='bold'?brand.typography.headingWeight:brand.typography.bodyWeight}}>Klare Aussage, nachvollziehbare Evidenz</span></div>)}</div></section>
 <section className="doc-section" id="folientypen"><h2>Die {slides.length} Folientypen</h2><p>Öffne eine Folie für ihre Einsatzregeln, die Zonen und typische Fehler.</p>{['Struktur','Karten','Evidenz'].map(group=><div className="deck-group" key={group}><h3>{group}-Folien</h3><div className="slide-gallery">{slides.filter(s=>s.gruppe===group).map(s=><button key={s.id} onClick={()=>setSelected(s.id)}><RenderedSlide brand={brand.id} id={s.id}/><div><code>{s.id}</code><h3>{s.titel}</h3><p>{s.zweck}</p></div></button>)}</div></div>)}</section>
 <section className="doc-section" id="presets"><h2>Deck-Presets für den Anlass</h2><p>Jede Folge erklärt die Reihenfolge und die Aufgabe jeder Folie.</p>{presets.map(p=><article className="deck-preset" key={p.id}><div className="deck-preset-heading"><div><h3>{p.titel}</h3><p>{p.zweck}</p></div><a href={`${download}/${p.id}.pptx`} download><Download size={15}/>{p.folgen.length} Folien · PPTX</a><a href={`${base}/reference/${p.id}.pdf`} download>PDF</a></div><div className="preset-filmstrip" aria-label={`Folienfolge ${p.titel}`}>{p.folgen.map((f,i)=><button key={`${f.typ}-${i}`} onClick={()=>setSelected(f.typ)}><RenderedSlide brand={brand.id} id={f.typ}/><span><b>{i+1}</b> {slides.find(s=>s.id===f.typ)?.titel}</span><small>{f.hinweis}</small></button>)}</div><p className="preset-story"><strong>Dramaturgie:</strong> {p.dramaturgie}</p></article>)}</section>
 <section className="doc-section" id="grundregeln"><h2>Die sechs Grundregeln</h2><div className="deck-rules">{rules.map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><aside className="anti-pattern"><TriangleAlert size={22}/><div><h3>Negativbeispiel: eine unbelegte Kennzahlensammlung</h3><p>Unverbundene Zahlen, beliebige Farben, fehlende Vergleichsperioden und keine Quellenzeile ergeben keine Management-Aussage. Der Inhaltsvalidator weist solche Projektdecks zurück.</p></div></aside></section>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="deck-detail"><DialogTitle>{selectedType?.titel}</DialogTitle><DialogDescription>{selectedType?.zweck}</DialogDescription>{selectedType&&<div className="deck-detail-grid"><div><RenderedSlide brand={brand.id} id={selectedType.id} large/><p className="muted">{selectedType.id} · aus muster-deck.pptx</p></div><div><h3>Was kommt in welche Zone?</h3><dl>{selectedType.zonen.map(z=><div key={z.zone}><dt>{z.zone}</dt><dd>{z.inhalt}</dd></div>)}</dl>{selectedType.dataviz&&<p className="detail-rule"><strong>Datenvisualisierung</strong>{selectedType.dataviz}</p>}<p className="detail-rule"><strong>Typischer Fehler</strong>{selectedType.fehler}</p><a href={`${download}/muster-deck.pptx`} download>Muster-Deck herunterladen</a></div></div>}<div className="deck-detail-nav"><Button variant="outline" onClick={()=>move(-1)}><ArrowLeft size={16}/>Vorherige</Button><span>{slides.findIndex(s=>s.id===selected)+1} / {slides.length}</span><Button variant="outline" onClick={()=>move(1)}>Nächste<ArrowRight size={16}/></Button></div></DialogContent></Dialog>
 </>;
}
