'use client';
import {useState} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {ArrowUpRight,Copy,Play} from 'lucide-react';
import {Button,Input,Dialog,DialogContent,DialogTitle,DialogDescription,Tabs,TabsList,TabsTrigger,TabsContent} from '@rapold/framework-core';
import {resolveFoundation,semanticTokens,contrast} from '@rapold/framework-brands';
import {presentationTheme,slides,presets} from '../../../../packages/brands/src/presentation.mjs';
import {useActiveBrand} from './framework-shell';
import {compilePrompt} from '../../../../packages/brands/src/prompt-compiler.mjs';
import {pages,guidance,guidanceFor,href} from './catalog';
import {SlidePreview} from './slide-preview';
import {ComponentDemo,componentNames} from './component-demo';
const BrandShowcase=dynamic(()=>import('./brand-showcase'));
const MermaidShowcase=dynamic(()=>import('./mermaid-showcase'),{loading:()=> <p>Diagrammgalerie wird geladen …</p>});
const PatternShowcase=dynamic(()=>import('./pattern-showcase'),{loading:()=> <p>Beispiel wird geladen …</p>});
const TableShowcase=dynamic(()=>import('./table-showcase'),{loading:()=> <p>Tabelle wird geladen …</p>});
const DataShowcase=dynamic(()=>import('./data-showcase'),{loading:()=> <p>Datenbeispiel wird geladen …</p>});
const EChartsShowcase=dynamic(()=>import('./echarts-showcase'),{loading:()=> <p>ECharts wird geladen …</p>});
const OrgchartEditor=dynamic(()=>import('./orgchart-editor'),{loading:()=> <p>Organigramm wird geladen …</p>});
const IconGallery=dynamic(()=>import('./icon-gallery'),{loading:()=> <p>Icon-Katalog wird geladen …</p>});
const descriptions:Record<string,string>={mermaid:'Architektur, Abläufe und Zusammenhänge als Diagramm. Fünf ausführbare Muster nach Atlas, mit Brand-Farben, Vollbild und eigenem Editor.',brand:'Original-Assets, Farben, Schriften und Vorlagen der aktiven Marke.',overview:'Die Referenz für Interfaces, Präsentationen und markenfähige Anwendungen.',tokens:'Semantische Rollen, vollständige Skalen und maschinenlesbare Exporte aus derselben Quelle.',typography:'Schriftrollen für Interfaces und Präsentationen. Die aktive Brand bestimmt Schrift und Gewichte.',layout:'Wiederholbare Abstände, konsistente Proportionen und das vermessene Atlas-Seitenraster.',icons:'Der vollständige neutrale Lucide-Satz aus Atlas, mit Suche, Code und SVG-Download.',components:'Alle 19 exportierten Atlas-UI-Module, neutralisiert und an die aktive Brand gebunden.',praesentation:'18 Folientypen, fünf Deck-Presets und ein gemeinsames Fünf-Zonen-Gerüst. Abgeleitet aus der Atlas-Präsentationsreferenz.',motion:'Dauer, Easing und Bewegungsverhalten als gemeinsame Design-Tokens.',tables:'Kompakte Datentabellen nach Atlas: klare Typografie, Status-Badges, Suche, Sortierung und Pagination.',feedback:'Lade-, Leer-, Fehler- und Erfolgszustände aus denselben Komponenten.',coverage:'Nachvollziehbare Übernahme aus Atlas und der Status der verbleibenden Spezialmodule.'};
export default function ReferencePage({section='overview'}:{section?:string}){
 const {brand,mode}=useActiveBrand();const page=pages.find(p=>p.id===section)!;const pageGuidance=guidanceFor(section,brand.id);const tokens=resolveFoundation(brand),colors=semanticTokens(brand,mode),deck=presentationTheme(brand);
 const [query,setQuery]=useState(''),[copied,setCopied]=useState(''),[selected,setSelected]=useState<string|null>(null),[repo,setRepo]=useState('owner/repo'),[motionKey,setMotionKey]=useState(0);
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);setCopied('Kopiert');}catch{setCopied('Kopieren nicht verfügbar. Text bitte direkt markieren.');}};
 const prompt=compilePrompt({idea:`Analysiere das Repository ${repo.trim()||'owner/repo'}.`,format:'Präsentation',brand});

 return <><div className="page-heading"><div className="eyebrow">{page.group} <span>/ {brand.name}</span></div><h1>{page.title}</h1><p>{descriptions[section]??pageGuidance?.intro}</p><div className="page-meta"><span className="status-label">{brand.status==='draft'?'CI-Entwurf':'Framework-Standard'}</span><a href={section==='brand'?`/brands/${brand.id}/brand.json`:section==='mermaid'?`/brands/${brand.id}/mermaid.${mode}.json`:section==='praesentation'?`/brands/${brand.id}/presentation.json`:`/brands/${brand.id}/tokens.${mode}.json`}>Vertrag als JSON <ArrowUpRight size={13}/></a></div></div>
 {section==='overview'&&<><div className="metrics"><div><strong>19</strong><span>UI-Module</span></div><div><strong>{Object.keys(colors).length}</strong><span>Farbrollen pro Modus</span></div><div><strong>18</strong><span>Folientypen</span></div><div><strong>5</strong><span>Deck-Presets</span></div></div><div className="entry-grid">{pages.filter(p=>['tokens','components','praesentation','icons','techstack','agenten'].includes(p.id)).map(p=><Link href={href(p.id)} key={p.id}><span className="eyebrow">{p.group}</span><h2>{p.title}<ArrowUpRight size={20}/></h2><p>{descriptions[p.id]??guidance[p.id]?.intro}</p></Link>)}</div><section className="doc-section"><h2>Eine Brand, alle Ausprägungen</h2><p>Der Brand-Wechsel aktualisiert Navigation, Komponenten und Präsentationen gemeinsam. Atlas bestimmt Struktur und Muster. Gelieferte CI-Vorgaben bestimmen die Markenidentität.</p><Link href="/coverage">Übernahme und verbleibende Lücken ansehen</Link></section></>}
 {section==='tokens'&&<><div className="download-row"><a href={`/brands/${brand.id}/tokens.${mode}.json`}>JSON</a><a href={`/brands/${brand.id}/tokens.${mode}.css`}>CSS Custom Properties</a><a href={`/brands/${brand.id}/tokens.${mode}.dtcg.json`}>DTCG</a></div><Tabs defaultValue="semantic"><TabsList><TabsTrigger value="semantic">Farbrollen</TabsTrigger><TabsTrigger value="foundation">Skalen</TabsTrigger><TabsTrigger value="contrast">Kontraste</TabsTrigger></TabsList><TabsContent value="semantic"><Input aria-label="Token suchen" value={query} placeholder="Token suchen …" onChange={e=>setQuery(e.target.value)}/><div className="token-grid">{Object.entries(colors).filter(([k])=>k.includes(query.toLowerCase())).map(([key,value])=><button className="token-card" key={key} onClick={()=>copy(`var(--${key})`)} title="CSS-Variable kopieren"><div className="swatch" style={{background:value}}/><code>--{key}</code><span>{value}</span></button>)}</div></TabsContent><TabsContent value="foundation">{Object.entries(tokens).filter(([,v])=>typeof v==='object').map(([group,values])=><section className="doc-section" key={group}><h2>{group}</h2><div className="token-table">{Object.entries(values as Record<string,string|number>).map(([k,v])=><button key={k} onClick={()=>copy(`var(--${group.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}-${k})`)}><code>{k}</code><span>{v}</span></button>)}</div></section>)}</TabsContent><TabsContent value="contrast"><div className="data-table"><table><thead><tr><th>Vordergrund</th><th>Hintergrund</th><th>Verhältnis</th><th>AA Text</th></tr></thead><tbody>{[['foreground','background'],['muted-foreground','muted'],['primary-foreground','primary'],['primary-hover-foreground','primary-hover'],['success-foreground','success'],['warning-foreground','warning'],['destructive-foreground','destructive']].map(([fg,bg])=><tr key={fg}><td>{fg}</td><td>{bg}</td><td>{contrast(colors[fg],colors[bg]).toFixed(2)}:1</td><td>{contrast(colors[fg],colors[bg])>=4.5?'Bestanden':'Prüfen'}</td></tr>)}</tbody></table></div></TabsContent></Tabs><p role="status" className="copy-status">{copied}</p></>}
 {section==='typography'&&<><div className="notice">{brand.typography.family} · Text {brand.typography.bodyWeight} · Titel {brand.typography.headingWeight}</div>{Object.entries(tokens.fontSize as Record<string,string>).map(([role,size])=><div className="type-row" key={role}><code>{role}<small>{size}</small></code><span style={{fontSize:size,fontWeight:brand.typography.headingWeight}}>Klare Aussagen. Präzise Hierarchie.</span></div>)}<section className="doc-section"><h2>Präsentationen: 13 vermessene Rollen</h2><p>Die PPT-Skala stammt aus Atlas. Die Brand liefert Schriftfamilie und Gewichte. Ihre Grösse wird auf der Folie massstabsgetreu angewendet.</p><div className="token-table">{Object.entries(deck.typography.scale).map(([k,v]:[string,any])=><div key={k}><code>{k}</code><span>{v.pt} pt · {v.weight}</span></div>)}</div></section></>}
 {section==='layout'&&<><section className="doc-section"><h2>Abstandsskala</h2>{Object.entries(tokens.spacing as Record<string,string>).map(([key,value])=><div className="spacing-row" key={key}><code>space-{key}</code><div style={{width:value}}/><span>{value}</span></div>)}</section><section className="doc-section"><h2>Shell-Geometrie aus Atlas</h2><div className="token-table">{Object.entries(tokens.layout).map(([k,v])=><div key={k}><code>{k}</code><span>{String(v)}</span></div>)}</div></section><section className="doc-section"><h2>Responsive Raster</h2><div className="grid-demo">{Array.from({length:12},(_,i)=><div key={i}>{i+1}</div>)}</div><p>12 Spalten. Inhalt maximal {tokens.layout.content}, Lesebreite {tokens.layout.reading}. Abstandsskalen sind neutrale Ergänzungen; Brand-Overrides bleiben möglich.</p></section></>}
 {section==='icons'&&<IconGallery/>}
 {section==='mermaid'&&<MermaidShowcase/>}
 {section==='brand'&&<BrandShowcase/>}
 {section==='organigramm'&&<OrgchartEditor/>}
 {(section==='components'||section==='feedback')&&<><div className="component-index">{componentNames.map(n=><span key={n}>{n}</span>)}</div><ComponentDemo/></>}
 {section==='motion'&&<><div className="notice">Bewegung unterstützt Orientierung. Bei prefers-reduced-motion werden Animationen unterdrückt.</div><Button onClick={()=>setMotionKey(k=>k+1)}><Play size={16}/>Beispiele abspielen</Button><div className="motion-grid" key={motionKey}>{['fast','normal','slow'].map(k=><div key={k}><div className="motion-sample" style={{animationDuration:tokens.duration[k]}}/><h2>{k}</h2><code>{tokens.duration[k]}</code></div>)}</div><div className="token-table">{Object.entries(tokens.easing).map(([k,v])=><div key={k}><code>{k}</code><span>{String(v)}</span></div>)}</div></>}
 {section==='tables'&&<TableShowcase/>}
 {section==='dashboard'&&<DataShowcase section={section}/>}
 {section==='charts'&&<Tabs defaultValue="recharts"><TabsList aria-label="Diagrammbibliothek"><TabsTrigger value="recharts">Recharts</TabsTrigger><TabsTrigger value="echarts">Apache ECharts</TabsTrigger></TabsList><TabsContent value="recharts"><DataShowcase section="charts"/></TabsContent><TabsContent value="echarts"><EChartsShowcase/></TabsContent></Tabs>}
 {['toasts','empty-states','skeletons','lightbox','forms','auth-flow','login-pattern','mail-templates','prompt-compiler','prompt-vorlagen','health-status','marketing-hero'].includes(section)&&<PatternShowcase section={section}/>}
 {pageGuidance&&pageGuidance.sections.map(s=><section key={s.title} className="doc-section"><h2>{s.title}</h2><p>{s.body}</p>{s.items&&<ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul>}</section>)}
 {section==='engineering'&&<div className="download-row"><a href="/contracts/engineering.md">Vollständiger Engineering-Vertrag</a><a href="https://github.com/marcelrapold/design/blob/main/CHANGELOG.md">Changelog</a></div>}

 {section==='agenten'&&<><label>Repository<Input value={repo} onChange={e=>setRepo(e.target.value)}/></label><pre>{prompt}</pre><Button onClick={()=>copy(prompt)}>Prompt kopieren</Button><p role="status">{copied}</p><div className="download-row"><a href={`/brands/${brand.id}/llms.txt`}>Agenten-Einstieg · {brand.id==='neutral'?'Default':brand.name}</a><a href={`/brands/${brand.id}/management.md`}>Vollständiger Management-Ablauf</a></div></>}
 {section==='coverage'&&<><div className="notice">Referenz: Atlas-Commit 1c75c95417cc371040e1e24a0986213314b53c13. Ein übernommenes Modul ist noch kein Nachweis vollständiger visueller Parität.</div><div className="data-table"><table><thead><tr><th>Bereich</th><th>Umsetzung</th></tr></thead><tbody>{[['UI-Primitives','19 von 19 exportierten Modulen übernommen und neutralisiert'],['Navigation','Gruppen, Suche, Rail, Breadcrumbs und mobile Navigation'],['Design-Tokens','Alle neutralen Atlas-Farbrollen; zusätzliche Skalen, semantische Exporte und Brand-Overrides'],['Präsentation','18 Rezepte, fünf Presets, 13 Typorollen und vermessene Geometrie'],['Icons','Vollständiger neutraler Lucide-Satz, Suche, Import und SVG'],['Firmenassets','ZVV-spezifische Logos, Linienzeichen, Lotties und Infrastruktur bewusst ausgeschlossen'],['Spezial-Showcases','Mermaid mit fünf Atlas-Beispielen, Vollbild, Brand-Themes und SVG-/MMD-Export, TanStack-Tabelle, Recharts, Formular-, Login- und Mail-Muster ausführbar. Organigramm und Zuständigkeiten mit Atlas-Renderer, SVG- und HTML-Export. ECharts mit Balken, Donut, Zeitreihe, Heatmap und SVG-Export.'],...(brand.id==='goldbach'?[['Goldbach','Gelieferte CI integriert; Erweiterungen als Entwurf']]:[['Default-Preset','Neutrale Basis mit Hell und Dunkel; keine Firmenassets']])].map(([a,b])=><tr key={a}><td>{a}</td><td>{b}</td></tr>)}</tbody></table></div></>}
 </>;
}
