"use client";
import Link from 'next/link';
import {ArrowUpRight,Download} from 'lucide-react';
import {Button} from '@rapold/framework-core';
import {sygnum,contrast} from '@rapold/framework-brands';
import evidence from '../../../../../brands/sygnum/sources/sources.json';
const labels:Record<string,string>={coral:'Coral',ink:'Ink',slate:'Slate',lavender:'Lavender',mist:'Mist',frost:'Frost',lilac:'Lilac',rose:'Rose',magenta:'Magenta'};
export default function SygnumShowcase(){
 const c=sygnum.modes.light;
 return <>
  <section className="active-brand-card" aria-label="Aktives Theme Sygnum">
   <div className="active-brand-mark"><img src="/brands/sygnum/logo.png" width={200} height={54} alt="Sygnum · Original-Presse-Logo"/></div>
   <div><p className="eyebrow">Sygnum · Research-basierter Design-Stack</p><h2>Tradition und digitale Zukunft.</h2><p>Öffentliche Quellen · dokumentierte Ableitungen · Status draft</p></div>
  </section>
  <section className="sygnum-hero" aria-label="Illustratives Gestaltungsbeispiel">
   <div><p className="eyebrow">Gestaltungsbeispiel · keine Bankkommunikation</p><h2>Future Finance.<br/>Vertrauen als Designprinzip.</h2><div className="sygnum-rule"/><p>Eine ruhige institutionelle Basis. Präzise Typografie. Coral als gezielter Akzent. Raum für komplexe Informationen, ohne visuelle Unruhe.</p></div>
   <div className="sygnum-hero-aside"><div><strong>01</strong><span>Belegte Identität</span></div><div><strong>02</strong><span>Prüfbare Umsetzung</span></div><div><strong>03</strong><span>Offene Freigabe</span></div></div>
  </section>
  <div className="notice">Dies ist eine Rekonstruktion für das Framework, kein offizielles Sygnum-CI-Manual. Der Research-Bericht belegt Farben und Schriftnamen, nicht sämtliche UI-Regeln. Ohne lokal verfügbare Originalschriften greifen Fallbacks.</div>
  <section className="doc-section"><h2>Die beobachtete Farbwelt</h2><p>RGB-Füllungen aus dem offiziellen Crypto Market Outlook 2025. Die Farbnamen dienen diesem Adapter und sind keine behaupteten offiziellen CI-Bezeichnungen.</p><div className="brand-colours">{Object.entries(sygnum.palette??{}).map(([key,value])=><div key={key}><span style={{background:value}}/><strong>{labels[key]??key}</strong><code>{value}</code></div>)}</div></section>
  <section className="doc-section"><h2>Coral bleibt Identität. Lesbarkeit bleibt Pflicht.</h2><div className="sygnum-grid"><article><span className="sygnum-evidence-tag">Beobachtet</span><h3>Original-Coral</h3><p><code>{sygnum.palette?.coral}</code> erreicht auf Weiss {contrast(sygnum.palette!.coral,c.background).toFixed(2)}:1. Für grosse Akzente und dekorative Flächen, nicht für kleinen weissen Buttontext.</p><div className="sygnum-rule"/></article><article><span className="sygnum-evidence-tag">Framework-Ableitung</span><h3>Interaktive Farbrolle</h3><p><code>{c.primary}</code> erreicht mit Weiss {contrast(c.primary,c['primary-foreground']).toFixed(2)}:1. Der dunklere Ton gilt für Aktionen, Links und Fokus. Die Markenpalette wird dadurch nicht überschrieben.</p><Button asChild><a href="/tokens?brand=sygnum">Kontraste und Tokens prüfen</a></Button></article></div></section>
  <section className="doc-section"><h2>Typografie mit Herkunft</h2><div className="sygnum-grid"><article><span className="sygnum-evidence-tag">PDF-Fontmetadaten</span><h3>Neusa Next Std</h3><div className="sygnum-sample">Präzision.<br/>Mit Perspektive.</div><p className="sygnum-type-meta">Light, Regular, Medium im untersuchten PDF. Display- und Titelrollen: leicht, grosszügig, klar.</p></article><article><span className="sygnum-evidence-tag">PDF-Fontmetadaten</span><h3>Benton Sans</h3><p>Komplexität braucht eine belastbare Ordnung. Klare Begriffe, lesbare Daten und ein nachvollziehbarer Entscheidungsweg stehen vor dekorativen Effekten.</p><p className="sygnum-type-meta">Light, Book, Medium, Bold im untersuchten PDF. Fliesstext und analytische Inhalte. Fontdateien sind nicht enthalten.</p></article></div><p className="muted">Die Website referenziert Originalfamilien mit Inter/Arial-Fallback. PPTX-Dateien referenzieren die Originalschriften, betten sie aber nicht ein. PDF- und PNG-Vorschauen verwenden die auf dem Render-System verfügbaren Ersatzschriften. Eine typografische CI-Abnahme mit lizenzierten Originalfonts bleibt offen.</p></section>
  <section className="doc-section" id="logos"><h2>Original statt nachgezeichneter Wortmarke</h2><div className="sygnum-original-logo"><img src="/brands/sygnum/logo.png" width={400} height={108} alt="Sygnum-Wortmarke mit vernetztem Symbol aus einer Sygnum-Presseveröffentlichung"/></div><p>Das Presseasset ist ein Rasteroriginal mit 400 × 108 Pixeln. Es wurde verlustfrei als PNG verpackt, nicht neu gezeichnet. Proportionen und Farben bleiben erhalten. Der SVG-Master und verbindliche Schutzraumvorgaben fehlen; das zusätzliche Padding ist eine Framework-Ableitung.</p><div className="download-row"><a href="/brands/sygnum/logo.png" download><Download size={14}/> Presse-Logo · PNG</a><a href="/brands/sygnum/sources.json">Herkunft und Nutzungsstatus</a></div></section>
  <section className="doc-section"><h2>Eine Marke, zwei Bildwelten</h2><div className="sygnum-grid"><article><span className="sygnum-evidence-tag">Institutioneller Modus</span><h3>Ruhig. Sachlich. Strukturiert.</h3><p>Banking-Interfaces und Management-Inhalte erhalten Weissraum, dünne Linien, geordnete Tabellen und fokussierte Farbakzente. Risiken und Quellen stehen sichtbar neben der Aussage.</p></article><article><span className="sygnum-evidence-tag">Research und Kampagnen</span><h3>Expressiv, wenn es dem Thema dient.</h3><p>Der untersuchte Research-Titel arbeitet mit intensiven Lichtfarben und einer Bitcoin-Eskalator-Metapher. Solche Motive sind belegte Kampagnenmittel, kein Anlass für Neon-Dekoration im gesamten Interface.</p></article></div></section>
  <section className="doc-section"><h2>Quellen und Prüfstatus</h2><div className="sygnum-source-list">{evidence.sources.map(source=><a key={source.id} href={source.url} target="_blank" rel="noreferrer"><span>{source.title}<small>{source.review}</small></span><ArrowUpRight size={16} aria-hidden="true"/></a>)}</div><p className="muted">Stand: 11.09.2026. Formulargebundene Reports wurden nicht durch erfundene Angaben beschafft. Live-CSS war beim direkten Abruf geschützt; daher werden keine aktuellen Web-CSS-Tokens behauptet.</p></section>
  <section className="doc-section"><h2>Ein Preset für den gesamten Stack</h2><p>Semantische UI-Tokens, Komponenten, Tabellen, Mermaid und Präsentationen übernehmen dieses Theme. Originalpalette und barrierearme Rollen bleiben technisch getrennt.</p><div className="download-row"><Link href="/praesentation?brand=sygnum">Präsentationsgalerie</Link><Link href="/mermaid?brand=sygnum">Mermaid</Link><Link href="/tables?brand=sygnum">Tabellen</Link><a href="/brands/sygnum/decks/muster-deck.pptx" download>18 Folienrezepte · PPTX</a><a href="/brands/sygnum/reference/muster-deck.pdf" download>Vorschau · PDF</a><a href="/brands/sygnum/management.md">Management-Vertrag</a><a href="/brands/sygnum/DESIGN.md">DESIGN.md</a><a href="/brands/sygnum/IMAGERY.md">IMAGERY.md</a><a href="/brands/sygnum/tokens.light.css">CSS-Tokens</a><a href="/brands/sygnum/tokens.light.dtcg.json">DTCG</a><a href="/brands/sygnum/brand.json">Brand-JSON</a></div></section>
 </>;
}
