import test from 'node:test';
import assert from 'node:assert/strict';
import {validateDeck} from '../packages/brands/src/deck-validation.mjs';
import {brands,defineBrand,neutral,tokenDocument,dtcgTokens,toCssVariables} from '../packages/brands/src/index.mjs';
import {presentationTheme,presets,slides} from '../packages/brands/src/presentation.mjs';
import {slideScene} from '../packages/brands/src/slide-scene.mjs';
const evidence={id:'repo',path:'README.md',commit:'abc123',retrievedAt:'2026-09-11'};
const working={title:'Belegte Aussage',lead:{period:'2026',source:'repo'},sources:[evidence],takeaway:'Eine belegte Konsequenz',section:'project'};
const valid={decisionQuestion:'Nächste Phase freigeben?',sections:[{id:'project',title:'Projekt'}],slides:[{type:'agenda',title:'Agenda',items:['Projekt']},{...working,type:'karten-steckbrief',introducesSources:true},{...working,type:'kpi-board',metrics:[{value:5,unit:'Module',period:'2026',comparison:4,sourceId:'repo'}]},{...working,type:'entscheid-register',resolution:{kind:'decision',owner:'Projektleitung',dueDate:'2026-10-01'}}]};
test('deck contract accepts evidence chain and accountable section closure',()=>assert.equal(validateDeck(valid).valid,true));
test('deck contract catches the actual Atlas content failures',()=>{const bad=structuredClone(valid);bad.slides[0].items=['Falscher Titel'];delete bad.slides[1].introducesSources;delete bad.slides[2].metrics[0].comparison;bad.slides[2].alarmCount=2;delete bad.slides[3].resolution.owner;const codes=validateDeck(bad).errors.map(e=>e.code);for(const c of ['agenda','sources-first','comparison','alarm-limit','accountability'])assert.ok(codes.includes(c),c);});
test('evidence must match the metric and must have been introduced earlier',()=>{const bad=structuredClone(valid);bad.slides[2].metrics[0].sourceId='unseen';const codes=validateDeck(bad).errors.map(e=>e.code);assert.ok(codes.includes('sources-first'));assert.ok(codes.includes('source-ref'));});
test('malformed input cannot silently pass or crash the deck validator',()=>{for(const change of [d=>{d.sections=[];d.slides=[];},d=>{d.slides[1].sources=[42];},d=>{d.slides[2].metrics[0].value={};},d=>{d.slides[3].resolution.dueDate='2026-02-31';},d=>{d.sections.push({...d.sections[0]});},d=>{d.slides[2].alarmCount=-1;}]){const d=structuredClone(valid);change(d);assert.equal(validateDeck(d).valid,false);}});
test('every preset resolves to implemented slide recipes and finite geometry',()=>{assert.equal(slides.length,18);assert.equal(presets.length,5);for(const brand of brands){const deck=presentationTheme(brand);assert.equal(Object.keys(deck.typography.scale).length,13);for(const preset of presets)for(const f of preset.folgen)assert.ok(slides.some(s=>s.id===f.typ));for(const s of slides)for(const n of slideScene(s.id,deck).nodes)for(const k of ['x','y','w','h'])assert.ok(Number.isFinite(n[k])&&n[k]>=0,`${s.id}/${k}`);}});
test('brand foundation overrides propagate to CSS and exports; injection rejected',()=>{const custom=defineBrand({...structuredClone(neutral),tokens:{spacing:{4:'18px'}}});assert.equal(toCssVariables(custom)['--spacing-4'],'18px');assert.equal(tokenDocument(custom).foundation.spacing[4],'18px');assert.throws(()=>defineBrand({...structuredClone(neutral),tokens:{spacing:{4:'url(https://example.com)'}}}));for(const brand of brands){const tokens=dtcgTokens(brand);assert.equal(tokens.primary.$value.colorSpace,'srgb');assert.equal(tokens.spacing['4'].$value.unit,'px');}});
test('rendered-preview digest ignores brand metadata that never reaches a slide', async () => {
  const {renderedBrandKeys}=await import('../scripts/reference-cache.mjs');
  for(const key of ['version','status','sources','presentation','genAI'])assert.ok(!renderedBrandKeys.includes(key),`${key} must not invalidate 72 committed renderings`);
  for(const key of ['id','name','modes','typography','shape','assets'])assert.ok(renderedBrandKeys.includes(key),`${key} reaches the slide and must invalidate renderings`);
  const project=brand=>JSON.stringify(Object.fromEntries(renderedBrandKeys.map(k=>[k,brand[k]??null])));
  const documented={...structuredClone(brands.at(-1)),version:'9.9.9',status:'approved',sources:['brands/x/y.md'],presentation:{logoOnCover:false},genAI:{maxKeyVisualsPer12Slides:1}};
  assert.equal(project(documented),project(brands.at(-1)),'documentation-only edits must not force a re-render');
  const repainted={...structuredClone(brands.at(-1)),modes:{light:{...brands.at(-1).modes.light,primary:'#010203'}}};
  assert.notEqual(project(repainted),project(brands.at(-1)),'a changed colour must force a re-render');
});
