import foundation from './deck-foundation.json' with { type:'json' };
import presets from './deck-presets.json' with { type:'json' };
import slides from './slide-catalog.json' with { type:'json' };
export { presets, slides };
export function presentationTheme(brand) {
 const c=brand.modes.light;
 const mix=(a,b,t)=>'#'+[0,2,4].map(i=>Math.round(parseInt(a.slice(1+i,3+i),16)*t+parseInt(b.slice(1+i,3+i),16)*(1-t)).toString(16).padStart(2,'0')).join('');
 const colors={background:c.card,text:c.foreground,muted:c['muted-foreground'],accent:c.primary,onAccent:c['primary-foreground'],primary:c.primary,'on-color':c['primary-foreground'],surface:c.card,'text-secondary':c['muted-foreground'],'text-muted':c['muted-foreground'],'surface-info':mix(c.primary,c.card,.08),'surface-neutral':c.muted,'surface-danger':mix(c.destructive,c.card,.08),border:c.border,success:c.success,warning:c.warning,danger:c.destructive,signal:c.destructive,'chart-2':c['primary-hover'],'chart-previous':c['muted-foreground']};
 return {schemaVersion:2,contentContract:'https://design.rapold.io/contracts/presentation-logic.md',validationCommand:'node scripts/validate-deck.mjs deck.json',brand:{id:brand.id,version:brand.version,status:brand.status},canvas:{ratio:'16:9',widthInches:13.333333,heightInches:7.5,...foundation.canvas},typography:{family:brand.typography.family.split(',')[0].trim(),titlePt:30,headingPt:13,bodyPt:10.5,notePt:8,bodyWeight:brand.typography.bodyWeight,headingWeight:brand.typography.headingWeight,scale:foundation.typeScale},colors,layout:{...foundation.zones,columns:foundation.columns,shapes:foundation.shapes,provenance:foundation.source},shape:{cornerRadiusPx:Number.parseFloat(brand.shape.radius)},numberFormat:foundation.numberFormat,slides,presets,evidence:{required:true,location:'speaker-notes',fields:['repository','commit','path','claimType'],allowedClaimTypes:['fact','inference','open-question']},assets:{logo:'original supplied brand asset, preserve proportions and clear space',imagery:'brand imagery rules; supplied images only for photographic layouts'},outputs:['editable-pptx','pdf','sources.json']};
}
